#!/usr/bin/env bun
/**
 * Regenerate `src/utils/nerd-font-glyphs.txt`, the Nerd Fonts name → codepoint
 * catalog that validates the icon names session titles ask for.
 *
 * Source: the official `glyphnames.json` (MIT, https://github.com/ryanoasis/nerd-fonts)
 * at the pinned release below. After two `#` comment lines, one sorted entry per
 * line, `<class>-<name> <hex codepoint>`:
 *
 *   md-flask f0093
 *
 * Every entry sits between a leading and a trailing newline, so the runtime finds
 * `nf-md-flask` with a plain search for "\nmd-flask " instead of parsing the file.
 *
 * Usage: bun scripts/generate-nerd-font-glyphs.ts [--version 3.4.0]
 */
import * as path from "node:path";

const args = process.argv.slice(2);
const versionFlag = args.indexOf("--version");
const version = versionFlag === -1 ? "3.4.0" : args[versionFlag + 1];
if (!version) throw new Error("--version needs a value");

const url = `https://raw.githubusercontent.com/ryanoasis/nerd-fonts/v${version}/glyphnames.json`;
const response = await fetch(url);
if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
// `glyphnames.json` maps `<class>-<name>` to `{ char, code }`, plus one METADATA record.
const catalog = (await response.json()) as Record<string, { code?: string }>;

const entries: string[] = [];
for (const key in catalog) {
	const value = catalog[key]!;
	if (key === "METADATA" || typeof value.code !== "string") continue;
	const codepoint = Number.parseInt(value.code, 16);
	// The runtime search relies on names never containing the space or newline delimiters.
	if (!/^[a-z0-9_]+-[a-z0-9_-]+$/.test(key) || !Number.isInteger(codepoint)) {
		throw new Error(`unexpected glyphnames.json entry ${key}`);
	}
	entries.push(`${key} ${codepoint.toString(16)}`);
}
entries.sort();

const lines = [
	`# Nerd Fonts ${version} glyph names (glyphnames.json, MIT, https://github.com/ryanoasis/nerd-fonts).`,
	"# Generated by scripts/generate-nerd-font-glyphs.ts; do not edit.",
	...entries,
];

const output = path.join(import.meta.dir, "../src/utils/nerd-font-glyphs.txt");
await Bun.write(output, `${lines.join("\n")}\n`);
console.info(`${entries.length} glyphs → ${output}`);
