import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { resetSettingsForTest, Settings } from "@oh-my-pi/pi-coding-agent/config/settings";
import { assertEditableFile } from "@oh-my-pi/pi-coding-agent/tools/auto-generated-guard";
import { resolveImageOptions } from "@oh-my-pi/pi-coding-agent/tools/render-utils";
import { ToolError } from "@oh-my-pi/pi-coding-agent/tools/tool-errors";

let tempDir: string;
let testSettings: Settings;
const GENERATED_TYPESCRIPT = "// Code generated by sqlc. DO NOT EDIT.\n\nexport const foo = 1;";

const CATALOG_PROTOCOL_DECLARATIONS = [
	path.resolve(import.meta.dir, "../../../catalog/src/discovery/cursor-proto.ts"),
	path.resolve(import.meta.dir, "../../../catalog/src/discovery/devin-proto.ts"),
];

beforeAll(async () => {
	resetSettingsForTest();
	tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "auto-gen-guard-"));
	testSettings = Settings.isolated();
});

afterAll(async () => {
	resetSettingsForTest();
	await fs.rm(tempDir, { recursive: true, force: true });
});

async function checkContent(content: string, fileName: string, activeSettings?: Settings): Promise<void> {
	const filePath = path.join(tempDir, fileName);
	await Bun.write(filePath, content);
	await assertEditableFile(filePath, fileName, activeSettings);
}

describe("assertEditableFile", () => {
	it("detects canonical TypeScript generated header", async () => {
		await expect(checkContent(GENERATED_TYPESCRIPT, "canonical.ts", testSettings)).rejects.toBeInstanceOf(ToolError);
	});

	it("detects @generated marker", async () => {
		await expect(
			checkContent("// @generated\n\nexport const foo = 1;", "marker.ts", testSettings),
		).rejects.toBeInstanceOf(ToolError);
	});

	it("detects generated-by marker for Python files", async () => {
		await expect(checkContent("# Generated by buf\n\nvalue = 1", "test.py", testSettings)).rejects.toBeInstanceOf(
			ToolError,
		);
	});

	it("detects generated-by marker for SQL files", async () => {
		await expect(checkContent("-- generated by sqlc\n\nselect 1;", "query.sql", testSettings)).rejects.toBeInstanceOf(
			ToolError,
		);
	});

	it("detects generated markers in leading block comments", async () => {
		const content = "/*\n * Code generated by mockery. DO NOT EDIT.\n */\nexport const foo = 1;";
		await expect(checkContent(content, "block.ts", testSettings)).rejects.toBeInstanceOf(ToolError);
	});

	it("detects kysely-codegen generated header", async () => {
		const content =
			"/**\n * This file was generated by kysely-codegen.\n * Please do not edit it manually.\n */\n\nexport interface Database {}";
		await expect(checkContent(content, "db.ts", testSettings)).rejects.toBeInstanceOf(ToolError);
	});

	it("defaults to blocking when global settings are uninitialized", async () => {
		resetSettingsForTest();
		await expect(checkContent(GENERATED_TYPESCRIPT, "global.ts")).rejects.toBeInstanceOf(ToolError);
	});

	it("honors isolated session settings without global initialization", async () => {
		const permissiveSettings = Settings.isolated({ "edit.blockAutoGenerated": false });
		await expect(checkContent(GENERATED_TYPESCRIPT, "permissive.ts", permissiveSettings)).resolves.toBeUndefined();
	});
});

describe("resolveImageOptions", () => {
	it("uses schema defaults when global settings are uninitialized", () => {
		resetSettingsForTest();
		const options = resolveImageOptions();
		expect(options.maxWidthCells).toBe(100);
		expect(options.maxHeightCells).toBeGreaterThan(0);
	});
});

describe("assertEditableFile path handling", () => {
	it("detects content marker from file prefix", async () => {
		const filePath = path.join(tempDir, "service.ts");
		await Bun.write(filePath, "// Code generated by sqlc. DO NOT EDIT.\nexport const foo = 1;");
		await expect(assertEditableFile(filePath, undefined, testSettings)).rejects.toBeInstanceOf(ToolError);
	});

	it("blocks generated catalog protocol declarations", async () => {
		for (const filePath of CATALOG_PROTOCOL_DECLARATIONS) {
			await expect(assertEditableFile(filePath, undefined, testSettings)).rejects.toBeInstanceOf(ToolError);
		}
	});

	it("allows normal files", async () => {
		const filePath = path.join(tempDir, "normal.ts");
		await Bun.write(filePath, "// Regular source file\nexport const foo = 1;");
		await expect(assertEditableFile(filePath, undefined, testSettings)).resolves.toBeUndefined();
	});

	it("handles missing files gracefully", async () => {
		const filePath = path.join(tempDir, "does-not-exist.ts");
		await expect(assertEditableFile(filePath, undefined, testSettings)).resolves.toBeUndefined();
	});
});
