/**
 * Wire definitions for session state snapshots and command results.
 *
 * Fields wrapped in `absentAs` were added after the first protocol release (or
 * are informational); decoders substitute the default when an older server
 * omits them.
 */
import { absentAs, doc, type WireDefs } from "./dsl";

const JSON_OBJECT = "Record<string, unknown>";

export const stateDefs = {
	QueueMode: "'all' | 'one-at-a-time'",
	InterruptMode: "'immediate' | 'wait'",
	StreamingBehavior: "'steer' | 'followUp'",
	QueuedMessageQueue: "'steering' | 'followUp'",
	CacheWarmingMode: "'off' | 'streaming' | 'idle'",
	MessageUpdates: doc(
		"'full' | 'delta'",
		"`set_event_filter` projection: `delta` drops the accumulated snapshots from `message_update`.",
	),
	TodoStatus: "'pending' | 'in_progress' | 'completed' | 'abandoned' | 'blocked'",
	GoalOp: "'get' | 'create' | 'resume' | 'pause' | 'drop'",
	GoalStatus: "'active' | 'paused' | 'budget-limited' | 'complete' | 'dropped'",
	SlashCommandSource: "'builtin' | 'skill' | 'extension' | 'custom' | 'mcp_prompt' | 'file'",
	SubagentSubscriptionLevel: doc(
		"'off' | 'progress' | 'events'",
		"Forwarded subagent frames: none, lifecycle and progress, or also raw session events.",
	),
	AgentSource: "'bundled' | 'user' | 'project'",
	SubagentStatus: "'pending' | 'running' | 'completed' | 'failed' | 'aborted'",

	TodoItem: {
		content: "string",
		status: "TodoStatus",
		"blocker?": doc("string", "What a `blocked` task is waiting on."),
		"details?": "string",
		"notes?": "string[]",
	},
	TodoPhase: { name: "string", tasks: "TodoItem[]" },
	ContextUsage: { tokens: "number.integer", contextWindow: "number.integer", percent: "number" },
	QueuedMessagesState: doc(
		{ steering: "string[]", followUp: "string[]" },
		"Displayable queue-chip text for pending user-authored messages; accepted verbatim by `remove_queued_message`.",
	),
	ToolDescriptor: { name: "string", description: "string", "parameters?": "unknown", "examples?": "unknown[]" },
	Goal: doc(
		{
			id: "string",
			objective: "string",
			status: "GoalStatus",
			"tokenBudget?": "number.integer",
			tokensUsed: "number.integer",
			timeUsedSeconds: "number",
			createdAt: "number.integer",
			updatedAt: "number.integer",
		},
		"A tracked goal: its objective, lifecycle status, and resource accounting.",
	),
	GoalModeState: doc(
		{ enabled: "boolean", mode: "'active' | 'exiting'", "reason?": "'completed'", goal: "Goal" },
		'Session goal mode; `mode` is `"exiting"` while a completed goal unwinds.',
	),
	GoalResult: doc(
		{ goal: "Goal | null", state: "GoalModeState | null" },
		"Outcome of every `goal` op; both fields are null when the session has no goal.",
	),
	SessionState: {
		"model?": "ModelInfo",
		"thinkingLevel?": "ThinkingLevel",
		isStreaming: absentAs("boolean", false),
		isCompacting: absentAs("boolean", false),
		steeringMode: absentAs("QueueMode", "one-at-a-time"),
		followUpMode: absentAs("QueueMode", "one-at-a-time"),
		interruptMode: absentAs("InterruptMode", "immediate"),
		"sessionFile?": "string",
		sessionId: "string",
		"sessionName?": "string",
		autoCompactionEnabled: absentAs("boolean", false),
		fastModeEnabled: absentAs("boolean", false),
		fastModeActive: absentAs("boolean", false),
		tokensPerSecond: absentAs("number | null", null),
		messageCount: absentAs("number.integer", 0),
		queuedMessageCount: absentAs("number.integer", 0),
		hasPendingAsyncWork: absentAs(
			doc("boolean", "Background jobs or deliveries can still inject a follow-up and wake the session."),
			false,
		),
		isSettled: absentAs(
			doc("boolean", "Idle with nothing queued or pending; same predicate as `session_settled`."),
			false,
		),
		queuedMessages: absentAs("QueuedMessagesState", { steering: [], followUp: [] }),
		todoPhases: absentAs("TodoPhase[]", []),
		systemPrompt: absentAs(doc("string[]", "System prompt sections, for session dumps."), []),
		dumpTools: absentAs("ToolDescriptor[]", []),
		"contextUsage?": "ContextUsage",
		goal: absentAs(doc("GoalModeState | null", "Current goal mode; null when the session has no goal."), null),
	},

	BashResult: {
		output: "string",
		"exitCode?": "number.integer",
		cancelled: "boolean",
		"timedOut?": "boolean",
		truncated: "boolean",
		totalLines: "number.integer",
		totalBytes: "number.integer",
		outputLines: "number.integer",
		outputBytes: "number.integer",
		"artifactId?": "string",
		"artifactElidedBytes?": "number.integer",
		"artifactError?": JSON_OBJECT,
		"workingDir?": "string",
		"images?": "ImageContent[]",
	},
	FastModeResult: { enabled: "boolean", active: "boolean" },
	CompactionResult: {
		summary: "string",
		"shortSummary?": "string",
		firstKeptEntryId: "string",
		tokensBefore: "number.integer",
		"details?": "unknown",
		"preserveData?": JSON_OBJECT,
	},
	ModelCycleResult: { model: "ModelInfo", "thinkingLevel?": "ThinkingLevel", isScoped: "boolean" },
	ThinkingLevelCycleResult: { level: "Effort" },
	CancellationResult: { cancelled: "boolean" },
	OpenSessionResult: doc(
		{ cancelled: "boolean", resumed: "boolean", sessionId: "string", "sessionFile?": "string" },
		"`open_session` outcome; `resumed` is false when a fresh session was started.",
	),
	RemoveQueuedMessageResult: { removed: "boolean" },
	PromoteQueuedMessageResult: { promoted: "boolean" },
	BranchMessage: { entryId: "string", text: "string" },
	BranchResult: { text: "string", cancelled: "boolean" },
	TokenUsage: {
		input: "number.integer",
		output: "number.integer",
		reasoning: absentAs("number.integer", 0),
		cacheRead: "number.integer",
		cacheWrite: "number.integer",
		total: "number.integer",
	},
	SessionCredits: { cost: "number", committedCost: "number", acuCost: "number" },
	SessionStats: {
		"sessionFile?": "string",
		sessionId: "string",
		userMessages: "number.integer",
		assistantMessages: "number.integer",
		toolCalls: "number.integer",
		toolResults: "number.integer",
		totalMessages: "number.integer",
		tokens: "TokenUsage",
		premiumRequests: "number",
		cost: "number",
		"credits?": "SessionCredits",
		"routedModels?": "Record<string, number>",
		"contextUsage?": "ContextUsage",
	},
	MessagesPage: {
		messages: "AgentMessage[]",
		totalMessages: "number.integer",
		"nextCursor?": doc("string", "Opaque cursor for the next page; absent on the last page."),
	},
	SlashCommandInput: { "hint?": "string" },
	SlashSubcommand: { name: "string", "description?": "string", "usage?": "string" },
	AvailableSlashCommand: {
		name: "string",
		"aliases?": "string[]",
		"description?": "string",
		"input?": "SlashCommandInput",
		"subcommands?": "SlashSubcommand[]",
		source: "SlashCommandSource",
	},
	SessionEntries: doc(
		{ entries: `${JSON_OBJECT}[]`, leafId: "string | null" },
		"OMP-native session entries in append order.",
	),
	SessionTree: doc({ tree: `${JSON_OBJECT}[]`, leafId: "string | null" }, "Raw session tree roots."),
	SubagentSnapshot: {
		id: "string",
		index: "number.integer",
		agent: "string",
		agentSource: "AgentSource",
		"description?": "string",
		status: "SubagentStatus",
		"task?": "string",
		"assignment?": "string",
		"sessionFile?": "string",
		lastUpdate: "number.integer",
		"progress?": doc(JSON_OBJECT, "Raw `AgentProgress` record."),
		"parentToolCallId?": "string",
	},
	SubagentMessages: doc(
		{
			sessionFile: "string",
			fromByte: "number.integer",
			nextByte: doc("number.integer", "Pass as the next `fromByte` to read incrementally."),
			reset: doc("boolean", "`fromByte` exceeded the file size and reading restarted at zero."),
			entries: `${JSON_OBJECT}[]`,
			messages: "AgentMessage[]",
		},
		"Incremental subagent transcript read.",
	),
	LoginProvider: { id: "string", name: "string", available: "boolean", authenticated: "boolean" },
	HandoffResult: { "savedPath?": "string" },
	PromptAck: doc(
		{ "agentInvoked?": "boolean" },
		"`agentInvoked: false` means the prompt completed locally and no `prompt_result` follows.",
	),
} satisfies WireDefs;
