/**
 * Streaming edit abort tests.
 */

import { afterEach, beforeEach, expect, it, vi } from "bun:test";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { type } from "@oh-my-pi/omptype";
import type { AgentEvent } from "@oh-my-pi/pi-agent-core";
import { Agent, type AgentTool } from "@oh-my-pi/pi-agent-core";
import type { AssistantMessage, StopReason, ToolCall } from "@oh-my-pi/pi-ai";
import { AssistantMessageEventStream } from "@oh-my-pi/pi-ai/utils/event-stream";
import { getBundledModel } from "@oh-my-pi/pi-catalog/models";
import { ModelRegistry } from "@oh-my-pi/pi-coding-agent/config/model-registry";
import { Settings } from "@oh-my-pi/pi-coding-agent/config/settings";
import { AgentSession } from "@oh-my-pi/pi-coding-agent/session/agent-session";
import { AuthStorage } from "@oh-my-pi/pi-coding-agent/session/auth-storage";
import { SessionManager } from "@oh-my-pi/pi-coding-agent/session/session-manager";
import { StreamingEditGuard } from "@oh-my-pi/pi-coding-agent/session/stream-guards";
import * as autoGeneratedGuard from "@oh-my-pi/pi-coding-agent/tools/auto-generated-guard";
import { ToolError } from "@oh-my-pi/pi-coding-agent/tools/tool-errors";
import { removeSyncWithRetries, Snowflake } from "@oh-my-pi/pi-utils";

function createAssistantMessage(content: AssistantMessage["content"], stopReason: StopReason): AssistantMessage {
	return {
		role: "assistant",
		content,
		api: "anthropic-messages",
		provider: "anthropic",
		model: "mock",
		usage: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
			totalTokens: 0,
			cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
		},
		stopReason,
		timestamp: Date.now(),
	};
}

function createToolCall(id: string, args: Record<string, unknown>): ToolCall {
	return {
		type: "toolCall",
		id,
		name: "edit",
		arguments: args,
	};
}

function lastAssistantMessage(messages: Array<{ role: string }>): AssistantMessage | undefined {
	for (let i = messages.length - 1; i >= 0; i--) {
		const msg = messages[i];
		if (msg.role === "assistant") return msg as AssistantMessage;
	}
	return undefined;
}

function createRng(seed: number): () => number {
	let state = seed % 2147483647;
	if (state <= 0) state += 2147483646;
	return () => {
		state = (state * 48271) % 2147483647;
		return state / 2147483647;
	};
}

function chunkStringRandomly(text: string, seed: number): string[] {
	const rand = createRng(seed);
	const chunks: string[] = [];
	let offset = 0;
	while (offset < text.length) {
		const remaining = text.length - offset;
		const maxSize = Math.min(8, remaining);
		const size = Math.max(1, Math.floor(rand() * maxSize) + 1);
		chunks.push(text.slice(offset, offset + size));
		offset += size;
	}
	return chunks;
}

async function createSession(
	tempDir: string,
	streamFn: Agent["streamFn"],
	tool: AgentTool,
): Promise<{ agent: Agent; session: AgentSession; authStorage: AuthStorage }> {
	const model = getBundledModel("anthropic", "claude-sonnet-4-5")!;
	const agent = new Agent({
		getApiKey: () => "test-key",
		initialState: {
			model,
			systemPrompt: ["Test"],
			tools: [tool],
		},
		streamFn,
	});

	const sessionManager = SessionManager.inMemory(tempDir);
	const settings = Settings.isolated({ "edit.streamingAbort": true });
	const authStorage = await AuthStorage.create(":memory:");
	authStorage.setRuntimeApiKey("anthropic", "test-key");
	const modelRegistry = new ModelRegistry(authStorage, path.join(tempDir, "models.yml"));

	return {
		agent,
		session: new AgentSession({
			agent,
			sessionManager,
			settings,
			modelRegistry,
		}),
		authStorage,
	};
}

function buildEditTool(): AgentTool {
	const schema = type({
		path: "string",
		diff: "string",
		op: "string?",
		rename: "string?",
	});

	return {
		name: "edit",
		label: "Edit",
		description: "",
		parameters: schema,
		async execute() {
			return { content: [{ type: "text", text: "ok" }] };
		},
	};
}

function buildReplaceEditTool(): AgentTool {
	const schema = type({
		path: "string",
		old_string: "string",
		new_string: "string",
	});
	return {
		name: "edit",
		label: "Edit",
		description: "",
		parameters: schema,
		async execute() {
			return {
				content: [{ type: "text", text: "Remote edit is unsupported" }],
				isError: true,
			};
		},
	};
}

function createStreamingEdit(
	path: string,
	chunks: string[],
	abortSignalRef: { current?: AbortSignal },
	createArguments: (path: string, streamedText: string) => Record<string, unknown>,
	streamStateRef?: { deltaCount: number; waitBeforeFirstDelta?: Promise<void>; waitBeforeFinish?: Promise<void> },
): Agent["streamFn"] {
	let callIndex = 0;
	return (_model, _context, options) => {
		abortSignalRef.current = options?.signal;
		const stream = new AssistantMessageEventStream();
		const toolCallId = "call_edit_1";
		let streamedText = "";
		let aborted = false;

		const notifyAbort = () => {
			if (aborted) return;
			aborted = true;
			const partialCall = createToolCall(toolCallId, createArguments(path, streamedText));
			stream.push({
				type: "toolcall_delta",
				contentIndex: 0,
				delta: "",
				partial: createAssistantMessage([partialCall], "stop"),
			});
			stream.push({ type: "error", reason: "aborted", error: createAssistantMessage([], "aborted") });
		};

		options?.signal?.addEventListener("abort", notifyAbort, { once: true });

		queueMicrotask(async () => {
			if (callIndex > 0) {
				const finalMessage = createAssistantMessage([{ type: "text", text: "done" }], "stop");
				stream.push({ type: "done", reason: "stop", message: finalMessage });
				callIndex++;
				return;
			}
			const startMessage = createAssistantMessage([], "stop");
			stream.push({ type: "start", partial: startMessage });

			const startCall = createToolCall(toolCallId, createArguments(path, ""));
			stream.push({ type: "toolcall_start", contentIndex: 0, partial: createAssistantMessage([startCall], "stop") });
			if (streamStateRef?.waitBeforeFirstDelta) {
				await streamStateRef.waitBeforeFirstDelta;
			}

			for (const chunk of chunks) {
				if (aborted) return;
				streamedText += chunk;
				if (streamStateRef) {
					streamStateRef.deltaCount += 1;
				}
				const partialCall = createToolCall(toolCallId, createArguments(path, streamedText));
				stream.push({
					type: "toolcall_delta",
					contentIndex: 0,
					delta: chunk,
					partial: createAssistantMessage([partialCall], "stop"),
				});
				// Yield a macrotask between deltas: real streamed tool calls arrive
				// across event-loop ticks, and the edit guard's async file cache only
				// settles across such ticks. Pure-microtask streams would finish the
				// whole turn before any I/O-backed verification can run.
				await Bun.sleep(0);
			}

			// Optional gate before the final events: lets a test hold the turn open
			// until the guard's async verification verdict has landed, instead of
			// racing `done` against I/O-backed verification.
			if (streamStateRef?.waitBeforeFinish) {
				await streamStateRef.waitBeforeFinish;
			}
			if (aborted) return;

			const finalCall = createToolCall(toolCallId, createArguments(path, streamedText));
			const finalMessage = createAssistantMessage([finalCall], "toolUse");
			stream.push({ type: "toolcall_end", contentIndex: 0, toolCall: finalCall, partial: finalMessage });
			stream.push({ type: "done", reason: "toolUse", message: finalMessage });
			callIndex++;
		});

		return stream;
	};
}

function createStreamForDiff(
	path: string,
	chunks: string[],
	abortSignalRef: { current?: AbortSignal },
	streamStateRef?: { deltaCount: number; waitBeforeFirstDelta?: Promise<void>; waitBeforeFinish?: Promise<void> },
): Agent["streamFn"] {
	return createStreamingEdit(
		path,
		chunks,
		abortSignalRef,
		(streamPath, diff) => ({ path: streamPath, diff }),
		streamStateRef,
	);
}

let tempDir: string;
const editTool = buildEditTool();
// One deterministic seed is enough to exercise the streaming abort decision: seed 7 splits
// each diff into 6 chunks and fragments the decision-critical context line (-beta / -omega)
// across deltas, driving the partial-parse abort logic through intermediate states. Multi-seed
// fan-out re-ran the full session machinery per seed (a fresh AuthStorage SQLite open each time)
// without adding meaningful coverage of the success/fail contracts.
const seeds = [7];
const STREAMING_EDIT_RANDOM_STREAM_TIMEOUT_MS = 20_000;

beforeEach(() => {
	tempDir = path.join(os.tmpdir(), `pi-streaming-edit-${Snowflake.next()}`);
	fs.mkdirSync(tempDir, { recursive: true });
});

afterEach(async () => {
	if (tempDir) {
		removeSyncWithRetries(tempDir);
	}
});

it(
	"does not abort for successful patches across random streams",
	async () => {
		await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\ngamma\n");
		const diff = "@@\n-beta\n+beta2\n";

		for (const seed of seeds) {
			const chunks = chunkStringRandomly(diff, seed);
			const abortSignalRef: { current?: AbortSignal } = {};
			const streamFn = createStreamForDiff("sample.txt", chunks, abortSignalRef);
			const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

			try {
				await session.prompt("apply patch");

				const lastAssistant = lastAssistantMessage(session.state.messages);
				expect(lastAssistant?.stopReason).not.toBe("aborted");
				expect(abortSignalRef.current?.aborted ?? false).toBe(false);
			} finally {
				try {
					await session.dispose();
				} finally {
					authStorage.close();
				}
			}
		}
	},
	STREAMING_EDIT_RANDOM_STREAM_TIMEOUT_MS,
);

it(
	"aborts for failing patches across random streams",
	async () => {
		// This test raced the fake provider against the guard's async
		// verification: Bun.sleep(0) between deltas does not guarantee the
		// Bun.file().text() load plus the verification chain settle before the
		// provider emits `done`, and the turn reset then correctly discards the
		// late verdict (CI flake: expected "aborted", received "stop"). Keep the
		// full session contract — event forwarding into the guard, agent.abort()
		// translated into an aborted turn and AbortSignal — but gate both async
		// legs explicitly: hold the target's file load open until every seed-7
		// fragmented delta (which splits the decision-critical `-omega` line)
		// has streamed, and hold the provider's final `done` until the released
		// verification has had its macrotasks to land the verdict.
		const target = path.join(tempDir, "sample.txt");
		await Bun.write(target, "alpha\nbeta\ngamma\n");
		const diff = "@@\n-omega\n+beta2\n";
		const chunks = chunkStringRandomly(diff, 7);
		const abortSignalRef: { current?: AbortSignal } = {};
		const finishGate = Promise.withResolvers<void>();
		const streamState = { deltaCount: 0, waitBeforeFinish: finishGate.promise };
		const streamFn = createStreamForDiff("sample.txt", chunks, abortSignalRef, streamState);
		const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

		const { promise: heldLoad, resolve: releaseLoad } = Promise.withResolvers<string>();
		const realFile = Bun.file.bind(Bun);
		const fileSpy = vi.spyOn(Bun, "file").mockImplementation(((pathLike: string) => {
			const real = realFile(pathLike);
			if (pathLike !== target) return real;
			// Only .text() is held; the session may touch other BunFile members.
			return new Proxy(real, {
				get(obj, prop) {
					if (prop === "text") return () => heldLoad;
					const value = Reflect.get(obj, prop);
					return typeof value === "function" ? value.bind(obj) : value;
				},
			});
		}) as typeof Bun.file);

		const promptPromise = session.prompt("apply patch");
		let stopWaitingForDeltas = false;
		try {
			const first = await Promise.race([
				(async () => {
					while (!stopWaitingForDeltas && streamState.deltaCount < chunks.length) {
						await drainMacrotasks(1);
					}
					return "deltas" as const;
				})(),
				promptPromise.then(() => "prompt" as const),
			]);
			if (first === "prompt") throw new Error("Prompt completed before every streamed delta was emitted");
			stopWaitingForDeltas = true;

			// Every queued verification is still pending behind the held load, so
			// the abort decision cannot have raced the stream.
			expect(abortSignalRef.current?.aborted ?? false).toBe(false);

			releaseLoad("alpha\nbeta\ngamma\n");
			await heldLoad;
			await drainMacrotasks(10);
			finishGate.resolve();
			await promptPromise;

			const lastAssistant = lastAssistantMessage(session.state.messages);
			expect(lastAssistant?.stopReason).toBe("aborted");
			expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		} finally {
			stopWaitingForDeltas = true;
			releaseLoad("alpha\nbeta\ngamma\n");
			finishGate.resolve();
			await promptPromise.catch(() => undefined);
			fileSpy.mockRestore();
			try {
				await session.dispose();
			} finally {
				authStorage.close();
			}
		}
	},
	STREAMING_EDIT_RANDOM_STREAM_TIMEOUT_MS,
);

it("does not abort when auto-generated peek fails with ENOENT (non-ToolError)", async () => {
	const checkSpy = vi
		.spyOn(autoGeneratedGuard, "assertEditableFile")
		.mockRejectedValue(Object.assign(new Error("ENOENT"), { code: "ENOENT" }));

	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\ngamma\n");
	const diff = "@@\n-beta\n+beta2\n";
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForDiff("sample.txt", chunkStringRandomly(diff, 7), abortSignalRef);
	const { agent, session, authStorage } = await createSession(tempDir, streamFn, editTool);
	const abortSpy = vi.spyOn(agent, "abort");

	try {
		await session.prompt("apply patch");

		expect(abortSpy).not.toHaveBeenCalled();
		expect(abortSignalRef.current?.aborted ?? false).toBe(false);
		const lastAssistant = lastAssistantMessage(session.state.messages);
		expect(lastAssistant?.stopReason).not.toBe("aborted");
	} finally {
		checkSpy.mockRestore();
		abortSpy.mockRestore();
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("aborts when auto-generated check rejects with ToolError", async () => {
	const checkSpy = vi
		.spyOn(autoGeneratedGuard, "assertEditableFile")
		.mockRejectedValue(new ToolError("Cannot modify auto-generated file"));

	await Bun.write(path.join(tempDir, "sample.txt"), "alpha\nbeta\ngamma\n");
	const diff = "@@\n-beta\n+beta2\n";
	const abortSignalRef: { current?: AbortSignal } = {};
	const streamFn = createStreamForDiff("sample.txt", chunkStringRandomly(diff, 7), abortSignalRef);
	const { agent, session, authStorage } = await createSession(tempDir, streamFn, editTool);
	const abortSpy = vi.spyOn(agent, "abort");

	try {
		await session.prompt("apply patch");

		expect(abortSpy).toHaveBeenCalled();
		expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		const lastAssistant = lastAssistantMessage(session.state.messages);
		expect(lastAssistant?.stopReason).toBe("aborted");
	} finally {
		checkSpy.mockRestore();
		abortSpy.mockRestore();
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("resolves local:// internal-scheme paths through the protocol handler instead of panicking", async () => {
	// Plan-mode persists the plan file under the synthetic local:// URL scheme.
	// Earlier the streaming pre-cache (#preCacheStreamingEditFile →
	// #getStreamingEditToolCall) called resolveToCwd() unconditionally on the
	// path, which throws for internal-scheme URLs via assertNotInternalUrl().
	// The throw escaped the synchronous interceptor as an Unhandled Rejection
	// and killed the session.
	//
	// The fix routes `local://` paths through resolveLocalUrlToPath() so they
	// map onto the session's on-disk local-artifacts directory; pre-caching,
	// auto-generated detection, and post-edit invalidation all run on the real
	// file. Drive a streaming Edit toolcall with path: 'local://PLAN.md' and
	// confirm the session completes without panicking and that
	// assertEditableFile is invoked with a real (non-internal-scheme) absolute
	// path so the auto-generated guard works for plan-mode edits too.
	const checkSpy = vi.spyOn(autoGeneratedGuard, "assertEditableFile");
	const diff = "@@\n-old\n+new\n";
	const abortSignalRef: { current?: AbortSignal } = {};
	const chunks = chunkStringRandomly(diff, 7);
	const streamFn = createStreamForDiff("local://PLAN.md", chunks, abortSignalRef);
	const { session, authStorage } = await createSession(tempDir, streamFn, editTool);

	try {
		await session.prompt("edit plan file");

		const lastAssistant = lastAssistantMessage(session.state.messages);
		expect(lastAssistant).toBeDefined();
		expect(lastAssistant?.stopReason).not.toBe("aborted");
		expect(abortSignalRef.current?.aborted ?? false).toBe(false);

		// Confirm pre-cache resolved the URL rather than skipping it: the
		// auto-generated guard should have been invoked with a concrete fs path
		// (absolute, no internal scheme) plus the original local:// display path.
		expect(checkSpy).toHaveBeenCalled();
		const [absolutePath, displayPath] = checkSpy.mock.calls[0] ?? [];
		expect(typeof absolutePath).toBe("string");
		expect(absolutePath).toMatch(/^(?:\/|[A-Za-z]:[\\/])/);
		expect(absolutePath).not.toMatch(/^[a-z]+:\/\//);
		expect(displayPath).toBe("local://PLAN.md");
	} finally {
		checkSpy.mockRestore();
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("keeps the session alive when replace mode streams an ssh:// path", async () => {
	const checkSpy = vi.spyOn(autoGeneratedGuard, "assertEditableFile");
	const abortSignalRef: { current?: AbortSignal } = {};
	const remotePath = "ssh://test-host/tmp/omp-repro.txt";
	const chunks = chunkStringRandomly("alpha", 7);
	const streamFn = createStreamingEdit(remotePath, chunks, abortSignalRef, (streamPath, oldText) => ({
		path: streamPath,
		old_string: oldText,
		new_string: "beta",
	}));
	const { session, authStorage } = await createSession(tempDir, streamFn, buildReplaceEditTool());

	try {
		expect(await session.prompt("edit remote file")).toBe(true);

		expect(checkSpy).not.toHaveBeenCalled();
		expect(abortSignalRef.current?.aborted ?? false).toBe(false);
		const lastAssistant = lastAssistantMessage(session.state.messages);
		expect(lastAssistant?.stopReason).not.toBe("aborted");
		const toolResult = session.state.messages.find(
			(message): message is Extract<typeof message, { role: "toolResult" }> =>
				message.role === "toolResult" && message.toolCallId === "call_edit_1",
		);
		expect(toolResult?.isError).toBe(true);
		expect(toolResult?.content).toContainEqual({ type: "text", text: "Remote edit is unsupported" });
	} finally {
		checkSpy.mockRestore();
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

it("aborts auto-generated file edits as soon as the path is available", async () => {
	const generatedPath = path.join(tempDir, "generated.ts");
	await Bun.write(generatedPath, "// Code generated by sqlc. DO NOT EDIT.\nexport const foo = 1;\n");
	const abortSignalRef: { current?: AbortSignal } = {};
	const diff = "@@\n-export const foo = 1;\n+export const foo = 2;\n";
	const chunks = chunkStringRandomly(diff, 7);
	const waitBeforeFirstDelta = Promise.withResolvers<void>();
	const streamState = { deltaCount: 0, waitBeforeFirstDelta: waitBeforeFirstDelta.promise };
	const streamFn = createStreamForDiff("generated.ts", chunks, abortSignalRef, streamState);
	const { agent, session, authStorage } = await createSession(tempDir, streamFn, editTool);
	const abortSpy = vi.spyOn(agent, "abort");
	const checkStarted = Promise.withResolvers<void>();
	const releaseCheck = Promise.withResolvers<void>();
	const checkSpy = vi.spyOn(autoGeneratedGuard, "assertEditableFile").mockImplementation(async () => {
		checkStarted.resolve();
		await releaseCheck.promise;
		throw new ToolError("Cannot modify auto-generated file");
	});

	try {
		const promptPromise = session.prompt("apply patch");
		await checkStarted.promise;

		expect(streamState.deltaCount).toBe(0);

		releaseCheck.resolve();
		waitBeforeFirstDelta.resolve();
		await promptPromise;

		expect(checkSpy).toHaveBeenCalledWith(generatedPath, "generated.ts", session.settings);
		expect(abortSpy).toHaveBeenCalled();
		expect(abortSignalRef.current?.aborted ?? false).toBe(true);
		const lastAssistant = lastAssistantMessage(session.state.messages);
		expect(lastAssistant?.stopReason).toBe("aborted");
	} finally {
		waitBeforeFirstDelta.resolve();
		releaseCheck.resolve();
		checkSpy.mockRestore();
		abortSpy.mockRestore();
		try {
			await session.dispose();
		} finally {
			authStorage.close();
		}
	}
});

// Builds a 2MB target whose tail matches the patch's removed lines, forcing
// verification to scan enough content to exercise its time-slicing path.
async function createLargeTargetSetup(abortCalls: { count: number }) {
	const target = path.join(tempDir, "big.txt");
	const fillerLine = `${"x".repeat(59)}\n`;
	const removedLines = Array.from({ length: 200 }, (_, i) => `removed-${i}-${"y".repeat(40)}`);
	const filler = fillerLine.repeat(Math.ceil((2 * 1024 * 1024) / fillerLine.length));
	await Bun.write(target, `${filler}${removedLines.map(line => `${line}\n`).join("")}`);

	const guard = new StreamingEditGuard({
		agent: {
			abort() {
				abortCalls.count += 1;
			},
		} as Agent,
		settings: Settings.isolated({ "edit.streamingAbort": true }),
		sessionManager: { getCwd: () => tempDir } as SessionManager,
		obfuscator: undefined,
		model: () => undefined,
		isDisposed: () => false,
		promptGeneration: () => 0,
		localProtocolOptions: () => ({}),
		emitNotice() {},
		schedulePostPromptTask() {},
		discardAssistantTurn() {},
	});

	const makeEvent = (eventType: "toolcall_start" | "toolcall_delta", streamedDiff: string): AgentEvent => {
		const message = createAssistantMessage(
			[createToolCall("call_edit_1", { path: target, diff: streamedDiff })],
			"stop",
		);
		return {
			type: "message_update",
			message,
			assistantMessageEvent: { type: eventType, contentIndex: 0, delta: "", partial: message },
		};
	};

	return { target, removedLines, guard, makeEvent };
}

/** Streams the diff in multi-line deltas paced across macrotasks like a real stream. */
async function streamDiff(
	guard: StreamingEditGuard,
	makeEvent: (t: "toolcall_start" | "toolcall_delta", d: string) => AgentEvent,
	diff: string,
): Promise<void> {
	guard.preCache(makeEvent("toolcall_start", ""));
	let streamed = "";
	for (let offset = 0; offset < diff.length; offset += 256) {
		streamed = diff.slice(0, offset + 256);
		const event = makeEvent("toolcall_delta", streamed);
		guard.preCache(event);
		guard.maybeAbort(event);
		// Macrotask pacing mirrors a real stream: the guard's async file cache and
		// time-sliced verdicts only settle across event-loop ticks.
		await Bun.sleep(0);
	}
	await Bun.sleep(0);
	await Bun.sleep(0);
}

it(
	"keeps the event loop responsive while prechecking a large-target edit",
	async () => {
		const abortCalls = { count: 0 };
		const { target, removedLines, guard, makeEvent } = await createLargeTargetSetup(abortCalls);
		const content = await Bun.file(target).text();
		const { promise: heldLoad, resolve: releaseLoad } = Promise.withResolvers<string>();
		const realFile = Bun.file.bind(Bun);
		const fileSpy = vi.spyOn(Bun, "file").mockImplementation(((pathLike: string) => ({
			text: () => (pathLike === target ? heldLoad : realFile(pathLike).text()),
		})) as typeof Bun.file);
		// Advance the guard's slice clock deterministically so the scan crosses its
		// time-slice boundary after each line regardless of real scan duration; the
		// responsiveness contract below is proven by an external task, not by the
		// clock or the guard's internal yield count.
		let nowMs = 0;
		const clockSpy = vi.spyOn(performance, "now").mockImplementation(() => {
			nowMs += 3;
			return nowMs;
		});

		try {
			const diff = `@@\n${removedLines.map(line => `-${line}`).join("\n")}\n-absent-line-xyz\n+replacement\n`;
			const event = makeEvent("toolcall_delta", diff);
			guard.preCache(event);
			guard.maybeAbort(event);

			// The streaming callback returns while the async target load is pending:
			// no synchronous scan blocks the caller.
			expect(guard.abortTriggered).toBe(false);
			expect(abortCalls.count).toBe(0);

			// Release the load, then race an independently scheduled macrotask against
			// the removed-lines scan. The absent line sits at the tail: a scan that
			// blocked the loop would reach it and abort before any other task could
			// run, so the beacon would observe an already-aborted guard. A responsive
			// scan yields first, letting the beacon run mid-flight.
			releaseLoad(content);
			const beacon = Promise.withResolvers<boolean>();
			setImmediate(() => beacon.resolve(guard.abortTriggered));
			const abortedWhenBeaconRan = await beacon.promise;
			expect(abortedWhenBeaconRan).toBe(false);

			// Draining the remaining slices completes the scan and surfaces the abort
			// the absent tail line must trigger.
			for (let i = 0; i < 400 && !guard.abortTriggered; i += 1) {
				await drainMacrotasks(1);
			}
			expect(guard.abortTriggered).toBe(true);
			expect(abortCalls.count).toBe(1);
		} finally {
			releaseLoad(content);
			clockSpy.mockRestore();
			fileSpy.mockRestore();
		}
	},
	STREAMING_EDIT_RANDOM_STREAM_TIMEOUT_MS,
);

it(
	"aborts when a streamed removed line is absent from current content",
	async () => {
		const abortCalls = { count: 0 };
		const { removedLines, guard, makeEvent } = await createLargeTargetSetup(abortCalls);
		// The absent line sits mid-diff so its verification completes while many
		// deltas are still streaming, keeping the async abort deterministic.
		const diffLines = [
			"@@",
			...removedLines.slice(0, 100).map(l => `-${l}`),
			"-absent-line-xyz",
			...removedLines.slice(100).map(l => `-${l}`),
			"+replacement",
		];
		const diff = `${diffLines.join("\n")}\n`;

		await streamDiff(guard, makeEvent, diff);
		// The time-sliced scan may need more ticks than the stream provided on a
		// slow machine; drain until the verdict lands (bounded, like the
		// responsiveness test above).
		for (let i = 0; i < 400 && !guard.abortTriggered; i += 1) {
			await drainMacrotasks(1);
		}

		expect(guard.abortTriggered).toBe(true);
		expect(abortCalls.count).toBe(1);
	},
	STREAMING_EDIT_RANDOM_STREAM_TIMEOUT_MS,
);

function buildSmallTargetGuard(target: string, toolCallId: string, abortCalls: { count: number }) {
	const guard = new StreamingEditGuard({
		agent: {
			abort() {
				abortCalls.count += 1;
			},
		} as Agent,
		settings: Settings.isolated({ "edit.streamingAbort": true }),
		sessionManager: { getCwd: () => tempDir } as SessionManager,
		obfuscator: undefined,
		model: () => undefined,
		isDisposed: () => false,
		promptGeneration: () => 0,
		localProtocolOptions: () => ({}),
		emitNotice() {},
		schedulePostPromptTask() {},
		discardAssistantTurn() {},
	});
	const makeEvent = (eventType: "toolcall_start" | "toolcall_delta", streamedDiff: string): AgentEvent => {
		const message = createAssistantMessage(
			[createToolCall(toolCallId, { path: target, diff: streamedDiff })],
			"stop",
		);
		return {
			type: "message_update",
			message,
			assistantMessageEvent: { type: eventType, contentIndex: 0, delta: "", partial: message },
		};
	};
	return {
		guard,
		makeEvent,
	};
}

it(
	"aborts early when the streamed edit targets an existing empty file",
	async () => {
		const abortCalls = { count: 0 };
		const target = path.join(tempDir, "empty.txt");
		await Bun.write(target, "");
		const { guard, makeEvent } = buildSmallTargetGuard(target, "call_edit_empty", abortCalls);
		const diff = "@@\n-absent-from-empty-file\n+replacement\n";
		const { promise: heldLoad, resolve: releaseLoad } = Promise.withResolvers<string>();
		const realFile = Bun.file.bind(Bun);
		const fileSpy = vi.spyOn(Bun, "file").mockImplementation(((pathLike: string) => ({
			text: () => (pathLike === target ? heldLoad : realFile(pathLike).text()),
		})) as typeof Bun.file);
		try {
			await streamDiff(guard, makeEvent, diff);
			releaseLoad("");
			await heldLoad;
			await drainMacrotasks(2);

			expect(guard.abortTriggered).toBe(true);
			expect(abortCalls.count).toBe(1);
		} finally {
			fileSpy.mockRestore();
		}
	},
	STREAMING_EDIT_RANDOM_STREAM_TIMEOUT_MS,
);

// Drains N macrotask ticks deterministically (no wall-clock delay) so queued
// promise callbacks and settled I/O continuations have all run.
async function drainMacrotasks(ticks: number): Promise<void> {
	for (let i = 0; i < ticks; i += 1) {
		const { promise, resolve } = Promise.withResolvers<void>();
		setImmediate(resolve);
		await promise;
	}
}

it("drops a queued removed-lines verification whose turn was reset before it started", async () => {
	const abortCalls = { count: 0 };
	const target = path.join(tempDir, "stale.txt");
	await Bun.write(target, "alpha\nbeta\n");
	const { guard, makeEvent } = buildSmallTargetGuard(target, "call_edit_stale", abortCalls);
	const diff = "@@\n-missing-line-xyz\n+replacement\n";

	// Hold the target's async load open so the queued verification is still
	// pending when the turn ends: reset() runs at every turn_start without
	// advancing the session's promptGeneration (which only moves on abort or
	// session-reset), so only the guard's internal epoch can drop the stale
	// check. It must not repopulate the cache under the next turn and abort it
	// once the load eventually settles.
	const { promise: heldLoad, resolve: releaseLoad } = Promise.withResolvers<string>();
	const realFile = Bun.file.bind(Bun);
	const fileSpy = vi.spyOn(Bun, "file").mockImplementation(((pathLike: string) => ({
		text: () => (pathLike === target ? heldLoad : realFile(pathLike).text()),
	})) as typeof Bun.file);
	try {
		const event = makeEvent("toolcall_delta", diff);
		guard.preCache(event);
		guard.maybeAbort(event);
		guard.reset();
		releaseLoad("alpha\nbeta\n");

		await heldLoad;
		await drainMacrotasks(10);

		expect(guard.abortTriggered).toBe(false);
		expect(abortCalls.count).toBe(0);
	} finally {
		fileSpy.mockRestore();
	}
});

it("drops queued removed-lines verifications when the edited file is invalidated", async () => {
	const abortCalls = { count: 0 };
	const target = path.join(tempDir, "invalidated.txt");
	await Bun.write(target, "alpha\nbeta\n");
	const { guard, makeEvent } = buildSmallTargetGuard(target, "call_edit_invalidated", abortCalls);

	// Queue two checks behind a held pre-edit read. Once the edit lands, neither
	// old check may start a fresh read and judge its old removals against the
	// post-edit content.
	const { promise: heldLoad, resolve: releaseLoad } = Promise.withResolvers<string>();
	const realFile = Bun.file.bind(Bun);
	let targetReads = 0;
	const fileSpy = vi.spyOn(Bun, "file").mockImplementation(((pathLike: string) => ({
		text: () => {
			if (pathLike !== target) return realFile(pathLike).text();
			targetReads += 1;
			return targetReads === 1 ? heldLoad : realFile(pathLike).text();
		},
	})) as typeof Bun.file);
	try {
		const first = makeEvent("toolcall_delta", "@@\n-alpha\n+replacement\n");
		guard.preCache(first);
		guard.maybeAbort(first);
		const second = makeEvent("toolcall_delta", "@@\n-alpha\n-beta\n+replacement\n");
		guard.preCache(second);
		guard.maybeAbort(second);

		await Bun.write(target, "replacement\n");
		guard.invalidate(target);
		releaseLoad("alpha\nbeta\n");

		await heldLoad;
		await drainMacrotasks(10);

		expect(targetReads).toBe(1);
		expect(guard.abortTriggered).toBe(false);
		expect(abortCalls.count).toBe(0);
	} finally {
		fileSpy.mockRestore();
	}
});
