import { afterEach, beforeAll, beforeEach, describe, expect, it } from "bun:test";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import type { AgentToolResult } from "@oh-my-pi/pi-agent-core";
import { InternalUrlRouter } from "@oh-my-pi/pi-coding-agent/internal-urls/router";
import type { ProtocolHandler } from "@oh-my-pi/pi-coding-agent/internal-urls/types";
import { Settings } from "@oh-my-pi/pi-coding-agent/config/settings";
import type { ClientBridge } from "@oh-my-pi/pi-coding-agent/session/client-bridge";
import type { ToolSession } from "@oh-my-pi/pi-coding-agent/tools";
import { wrapToolWithMetaNotice } from "@oh-my-pi/pi-coding-agent/tools/output-meta";
import { ReadTool } from "@oh-my-pi/pi-coding-agent/tools/read";
import { WriteTool } from "@oh-my-pi/pi-coding-agent/tools/write";
import { readArchiveEntries, writeArchive } from "@oh-my-pi/pi-utils/ar";

import { cfgReadDefaultLimit } from "@oh-my-pi/pi-coding-agent/tools/settings";

function createSession(cwd: string, bridge?: ClientBridge, editMode: "replace" | "hashline" = "replace"): ToolSession {
	return {
		cwd,
		hasUI: false,
		getSessionFile: () => path.join(cwd, "session.jsonl"),
		getSessionSpawns: () => "*",
		getArtifactsDir: () => path.join(cwd, "artifacts"),
		allocateOutputArtifact: async () => ({ id: "artifact-1", path: path.join(cwd, "artifact-1.log") }),
		settings: Settings.isolated({ "edit.blockAutoGenerated": false, "edit.mode": editMode }),
		enableLsp: false,
		getClientBridge: bridge ? () => bridge : undefined,
	};
}

function resultText(result: AgentToolResult): string {
	return result.content.flatMap(block => (block.type === "text" ? [block.text] : [])).join("\n");
}

describe("write tool read projection guard", () => {
	let tmpDir: string;

	beforeAll(async () => {
		await Settings.init({ inMemory: true });
	});

	beforeEach(async () => {
		tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "write-read-projection-test-"));
	});

	afterEach(async () => {
		InternalUrlRouter.resetForTests();
		await fs.rm(tmpDir, { recursive: true, force: true });
	});

	it.each([
		{
			name: "Showing lines notice",
			sourceLines: 60,
			visibleLines: 20,
			notice: "[Showing lines 1-20 of 60. Use :21 to continue]",
		},
		{
			name: "byte-budget Showing lines notice",
			sourceLines: 60,
			visibleLines: 20,
			notice: "[Showing lines 1-20 of 60 (50.0KB limit). Use :21 to continue]",
		},
		{
			name: "entity-labelled remaining-lines notice",
			sourceLines: 60,
			visibleLines: 20,
			notice: "[40 more lines in notebook. Use :21 to continue]",
		},
		{
			name: "unscanned remaining-lines notice",
			sourceLines: 60,
			visibleLines: 20,
			notice: "[More lines in file (120.0KB total; not scanned to EOF). Use :21 to continue]",
		},
		{
			name: "ASCII summary elision notice",
			sourceLines: 40,
			visibleLines: 10,
			notice: "[...30ln elided; re-read needed ranges, e.g. sample.txt:11-20,31-40]",
		},
		{
			name: "stale-total notice",
			sourceLines: 65,
			visibleLines: 20,
			notice: "[Showing lines 1-20 of 60. Use :21 to continue]",
		},
	])("rejects a shorter $name projection without changing the file", async ({ sourceLines, visibleLines, notice }) => {
		const filePath = path.join(tmpDir, "sample.txt");
		const originalLines = Array.from({ length: sourceLines }, (_, index) => `line ${index + 1}`);
		const original = `${originalLines.join("\n")}\n`;
		await Bun.write(filePath, original);
		const partial = `${originalLines.slice(0, visibleLines).join("\n")}\n${notice}\n`;

		await expect(
			new WriteTool(createSession(tmpDir)).execute("call-1", { path: filePath, content: partial }),
		).rejects.toThrow("incomplete read projection");
		expect(await Bun.file(filePath).text()).toBe(original);
	});

	it("rejects the actual bounded ReadTool output without changing the file", async () => {
		const filePath = path.join(tmpDir, "round-trip.txt");
		const original = `${Array.from({ length: 60 }, (_, index) => `line ${index + 1}`).join("\n")}\n`;
		await Bun.write(filePath, original);
		const session = createSession(tmpDir);
		cfgReadDefaultLimit.set(session.settings, 20);
		const projection = resultText(
			await wrapToolWithMetaNotice(new ReadTool(session)).execute("read-1", { path: filePath }),
		);
		expect(projection).toContain("[Showing lines 1-20 of 60. Use :21 to continue]");

		await expect(new WriteTool(session).execute("write-1", { path: filePath, content: projection })).rejects.toThrow(
			"incomplete read projection",
		);
		expect(await Bun.file(filePath).text()).toBe(original);
	});

	it("rejects bounded hashline output whose display prefixes make it longer than the source", async () => {
		const filePath = path.join(tmpDir, "hashline.txt");
		const original = "\n".repeat(60);
		await Bun.write(filePath, original);
		const session = createSession(tmpDir, undefined, "hashline");
		cfgReadDefaultLimit.set(session.settings, 20);
		const projection = resultText(
			await wrapToolWithMetaNotice(new ReadTool(session)).execute("read-hashline", { path: filePath }),
		);
		expect(projection).toContain("[Showing lines 1-20 of 60. Use :21 to continue]");
		expect(projection.length).toBeGreaterThan(original.length);

		await expect(
			new WriteTool(session).execute("write-hashline", { path: filePath, content: projection }),
		).rejects.toThrow("incomplete read projection");
		expect(await Bun.file(filePath).text()).toBe(original);
	});

	it("rejects a byte-truncated single-line projection that renders longer than its source", async () => {
		const filePath = path.join(tmpDir, "oneline.txt");
		// One line just past the 50KB read byte budget: the shown ~50KB prefix
		// plus its partial-line footer is longer than the source line, yet covers
		// strictly less of it. The marker, not rendered length, proves it partial.
		const original = `${"x".repeat(50 * 1024 + 10)}\n`;
		await Bun.write(filePath, original);
		const session = createSession(tmpDir);
		const projection = resultText(
			await wrapToolWithMetaNotice(new ReadTool(session)).execute("read-line", { path: `${filePath}:1-1` }),
		);
		expect(projection).toContain("(partial,");
		expect(projection.length).toBeGreaterThan(original.length);

		await expect(
			new WriteTool(session).execute("write-line", { path: filePath, content: projection }),
		).rejects.toThrow("incomplete read projection");
		expect(await Bun.file(filePath).text()).toBe(original);
	});

	it("rejects actual bounded archive-member output without changing the archive", async () => {
		const archivePath = path.join(tmpDir, "bundle.zip");
		const member = "member.txt";
		const original = `${Array.from({ length: 60 }, (_, index) => `line ${index + 1}`).join("\n")}\n`;
		await writeArchive(archivePath, "zip", [[member, original]]);
		const before = await Bun.file(archivePath).bytes();
		const session = createSession(tmpDir);
		const projection = resultText(
			await wrapToolWithMetaNotice(new ReadTool(session)).execute("read-archive", {
				path: `${archivePath}:${member}:1-20`,
			}),
		);
		expect(projection).toContain("[37 more lines in archive entry. Use :24 to continue]");

		await expect(
			new WriteTool(session).execute("write-archive", { path: `${archivePath}:${member}`, content: projection }),
		).rejects.toThrow("incomplete read projection");
		expect(await Bun.file(archivePath).bytes()).toEqual(before);
		const entries = await readArchiveEntries({ bytes: before, format: "zip" });
		expect(new TextDecoder().decode(entries.get(member))).toBe(original);
	});

	it("rejects actual bounded mutable-resource output before internal URL dispatch", async () => {
		const url = "vault://document";
		let resourceContent = `${Array.from({ length: 60 }, (_, index) => `resource ${index + 1}`).join("\n")}\n`;
		let writeCalled = false;
		const handler: ProtocolHandler = {
			scheme: "vault",
			spec: {
				backing: "virtual",
				selectors: "lines",
				immutable: false,
				write: { payload: "text", scope: "workspace", tier: () => "write" },
			},
			resolve: async resolvedUrl => ({
				url: resolvedUrl.href,
				content: resourceContent,
				contentType: "text/plain",
			}),
			write: async (_resolvedUrl, nextContent) => {
				writeCalled = true;
				resourceContent = nextContent;
			},
		};
		InternalUrlRouter.instance().register(handler);
		const session = createSession(tmpDir);
		const projection = resultText(
			await wrapToolWithMetaNotice(new ReadTool(session)).execute("read-url", { path: `${url}:1-20` }),
		);
		expect(projection).toContain("[37 more lines in resource. Use :24 to continue]");

		await expect(new WriteTool(session).execute("write-url", { path: url, content: projection })).rejects.toThrow(
			"incomplete read projection",
		);
		expect(writeCalled).toBe(false);
		expect(resourceContent).toContain("resource 60");
	});

	it("compares against the ACP buffer before bridge writes", async () => {
		const filePath = path.join(tmpDir, "bridge.txt");
		const diskContent = "disk\n";
		const bufferContent = `${Array.from({ length: 65 }, (_, index) => `buffer ${index + 1}`).join("\n")}\n`;
		await Bun.write(filePath, diskContent);
		let bridgeWriteCalled = false;
		let bridgeReadCalled = false;
		const bridge: ClientBridge = {
			capabilities: { readTextFile: true, writeTextFile: true },
			readTextFile: async () => {
				bridgeReadCalled = true;
				return bufferContent;
			},
			writeTextFile: async () => {
				bridgeWriteCalled = true;
			},
		};
		const partial = `${bufferContent.split("\n").slice(0, 20).join("\n")}\n[Showing lines 1-20 of 65. Use :21 to continue]\n`;

		await expect(
			new WriteTool(createSession(tmpDir, bridge)).execute("write-bridge", { path: filePath, content: partial }),
		).rejects.toThrow("incomplete read projection");
		expect(bridgeReadCalled).toBe(true);
		expect(bridgeWriteCalled).toBe(false);
		expect(await Bun.file(filePath).text()).toBe(diskContent);
	});

	it("writes a literal read notice when the replacement does not shrink the current source", async () => {
		const filePath = path.join(tmpDir, "documentation.txt");
		const content = "Example omp output:\n[Showing lines 1-20 of 60. Use :21 to continue]\n";
		await Bun.write(filePath, "old\n");

		await new WriteTool(createSession(tmpDir)).execute("call-2", { path: filePath, content });

		expect(await Bun.file(filePath).text()).toBe(content);
	});
});
