[package]
name = "pi-vcs"
version.workspace = true
edition.workspace = true
license = "MIT"
authors.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
gix.workspace = true
jj-lib.workspace = true
pi-iso.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[dev-dependencies]
tempfile = "3"
