//! Generated by `bun run gen:grammars` from stencil-hq/wasm-grammars v1; do
//! not edit.
//!
//! WebAssembly grammars published as `<file>.zst` assets of that release (see
//! [`super::grammar`]).

use super::grammar::WasmGrammar;

/// stencil-hq/wasm-grammars release tag hosting every grammar below.
pub const RELEASE: &str = "v1";

/// `tree-sitter-astro-next` 0.1.1.
pub static ASTRO: WasmGrammar = WasmGrammar::new(
	"astro",
	"astro",
	"astro-612c83b88b97ba7c.wasm",
	"612c83b88b97ba7cc53a4808aebf71196442d2aea70955333b114212b771a4d7",
	24622,
);

/// `tree-sitter-clojure` 0.1.0.
pub static CLOJURE: WasmGrammar = WasmGrammar::new(
	"clojure",
	"clojure",
	"clojure-f63ecd31939b06c3.wasm",
	"f63ecd31939b06c315c49794a628059b6f16de191a17b148a290e5f8faffbc0a",
	97934,
);

/// `tree-sitter-cmake` 0.7.5.
pub static CMAKE: WasmGrammar = WasmGrammar::new(
	"cmake",
	"cmake",
	"cmake-38a05d65733bf24f.wasm",
	"38a05d65733bf24f4469b01d644d6b8e26e779fcc40ae562037dd699aee6e103",
	75504,
);

/// `tree-sitter-c-sharp` 0.23.5.
pub static CSHARP: WasmGrammar = WasmGrammar::new(
	"csharp",
	"c_sharp",
	"csharp-f265130d20fe62d3.wasm",
	"f265130d20fe62d3dc0cec756ee5a4159bd9825894a48fc0f7e72c8bd30ef099",
	5328197,
);

/// `tree-sitter-dart` 0.2.0.
pub static DART: WasmGrammar = WasmGrammar::new(
	"dart",
	"dart",
	"dart-52bdbf469a2343a5.wasm",
	"52bdbf469a2343a52385f75dab61097fe9c157e747ddfcc52200c153c4259d4b",
	1269300,
);

/// `tree-sitter-dockerfile-updated` 0.2.0.
pub static DOCKERFILE: WasmGrammar = WasmGrammar::new(
	"dockerfile",
	"dockerfile",
	"dockerfile-6d95cfe08d32ad32.wasm",
	"6d95cfe08d32ad32cd4e3e13e209f03ae59fbd495ad61014e1873fbbbb6c5078",
	48699,
);

/// `tree-sitter-elixir` 0.3.5.
pub static ELIXIR: WasmGrammar = WasmGrammar::new(
	"elixir",
	"elixir",
	"elixir-1160c3b90a7c1eb7.wasm",
	"1160c3b90a7c1eb7cb8f8e5c3a1960db3219c97c10fa21b1421b79142cc2e556",
	1412268,
);

/// `tree-sitter-elisp` 1.7.2.
pub static EMACS_LISP: WasmGrammar = WasmGrammar::new(
	"emacs-lisp",
	"elisp",
	"emacs-lisp-d4fee941a25f6464.wasm",
	"d4fee941a25f646467cebe60317f46eb0f47b617c76fb9a1a60e7e7982b43415",
	52513,
);

/// `tree-sitter-erlang` 0.16.0.
pub static ERLANG: WasmGrammar = WasmGrammar::new(
	"erlang",
	"erlang",
	"erlang-bb8809212393e686.wasm",
	"bb8809212393e68687d0f2bc1309c4ca7601fa704a8a96edaffaa34585f1b1b7",
	418478,
);

/// `tree-sitter-fortran` 0.6.0.
pub static FORTRAN: WasmGrammar = WasmGrammar::new(
	"fortran",
	"fortran",
	"fortran-f72872963184cdb4.wasm",
	"f72872963184cdb4ccb623be3e4e40606066a317be6d5d61cdc929b51bba6d22",
	6591350,
);

/// `tree-sitter-graphql` 0.1.0.
pub static GRAPHQL: WasmGrammar = WasmGrammar::new(
	"graphql",
	"graphql",
	"graphql-fd4081c84308f5db.wasm",
	"fd4081c84308f5db14a4a6e1bea91c08f9c38e5ab47e5a0730c4a39448844d00",
	57563,
);

/// `tree-sitter-haskell` 0.23.1.
pub static HASKELL: WasmGrammar = WasmGrammar::new(
	"haskell",
	"haskell",
	"haskell-ddc4978970326bc4.wasm",
	"ddc4978970326bc46369f3dff15027c54dac79adb7aca9ba7b6d3a20ebb1b3e0",
	3805634,
);

/// `tree-sitter-hcl` 1.1.0.
pub static HCL: WasmGrammar = WasmGrammar::new(
	"hcl",
	"hcl",
	"hcl-1b4b186da007c489.wasm",
	"1b4b186da007c48980f7ec7259b15edb2ea6cb1b8cf7ad01d5c9c39456aa52fb",
	93351,
);

/// `tree-sitter-ini` 1.4.0.
pub static INI: WasmGrammar = WasmGrammar::new(
	"ini",
	"ini",
	"ini-4884a74e0e60d02f.wasm",
	"4884a74e0e60d02fc897b1f780c044e578ff839c9eeb6f4742d2feaef9839ece",
	4710,
);

/// `tree-sitter-julia` 0.23.1.
pub static JULIA: WasmGrammar = WasmGrammar::new(
	"julia",
	"julia",
	"julia-78d8e1aa3b207c29.wasm",
	"78d8e1aa3b207c290631bbb071ebbe20f91d631e91dd2d78a71358472660978a",
	6223351,
);

/// `tree-sitter-just` 0.2.0.
pub static JUST: WasmGrammar = WasmGrammar::new(
	"just",
	"just",
	"just-989d19dab6b34933.wasm",
	"989d19dab6b349337e0335e8f8bfe39de40f27639dc34c23a0d8c63678a69e68",
	44632,
);

/// `tree-sitter-kotlin-sg` 0.4.1.
pub static KOTLIN: WasmGrammar = WasmGrammar::new(
	"kotlin",
	"kotlin",
	"kotlin-83d1aa9580f91a32.wasm",
	"83d1aa9580f91a32b51a057ad4216166c29e488bf750aa891ae528f7a04dd4bf",
	5772696,
);

/// `tree-sitter-lua` 0.5.0.
pub static LUA: WasmGrammar = WasmGrammar::new(
	"lua",
	"lua",
	"lua-83446c583739247d.wasm",
	"83446c583739247d74ae0953a1844b642fc126a5e773b797ecd0f7b5af686c84",
	53205,
);

/// `tree-sitter-make` 1.1.1.
pub static MAKE: WasmGrammar = WasmGrammar::new(
	"make",
	"make",
	"make-c2a057ef58739b2f.wasm",
	"c2a057ef58739b2f8025bc3f7d04a62ae3daad8aeb7979b2db6097800950cded",
	147044,
);

/// `tree-sitter-nix` 0.3.0.
pub static NIX: WasmGrammar = WasmGrammar::new(
	"nix",
	"nix",
	"nix-10a66e15b62be1a5.wasm",
	"10a66e15b62be1a59cd256abf4b48fdeac07e50c0a8e50ceb64296fcec019930",
	79503,
);

/// `tree-sitter-objc` 3.0.2.
pub static OBJC: WasmGrammar = WasmGrammar::new(
	"objc",
	"objc",
	"objc-ede2d58688f085d4.wasm",
	"ede2d58688f085d4d36ccdf7f2b50aa61f70ea4f134dd3741c23ad857473a148",
	5317156,
);

/// `tree-sitter-ocaml` 0.24.2.
pub static OCAML: WasmGrammar = WasmGrammar::new(
	"ocaml",
	"ocaml",
	"ocaml-c60bd9980a698106.wasm",
	"c60bd9980a698106c09dccf5a089841e7d285721ad8ce9e4fd5a326bf3316d0f",
	5553927,
);

/// `tree-sitter-odin` 1.3.0.
pub static ODIN: WasmGrammar = WasmGrammar::new(
	"odin",
	"odin",
	"odin-0fa018a7182e62a6.wasm",
	"0fa018a7182e62a6414379018fb1bbe2e46ca39f6f1cd6584a4609481c1f303e",
	2215304,
);

/// `tree-sitter-php` 0.24.2.
pub static PHP: WasmGrammar = WasmGrammar::new(
	"php",
	"php_only",
	"php-cb7397cba44a21ce.wasm",
	"cb7397cba44a21ce6882d8173c597d66e32a257cb1f628ba45cdf23f9d8d7c6a",
	1002409,
);

/// `tree-sitter-powershell` 0.26.4.
pub static POWERSHELL: WasmGrammar = WasmGrammar::new(
	"powershell",
	"powershell",
	"powershell-2a24f946f96e67ac.wasm",
	"2a24f946f96e67ac812fb6c7d647576a033febc0c48f4c91a340b549e7eac73d",
	990743,
);

/// `tree-sitter-proto` 0.4.0.
pub static PROTOBUF: WasmGrammar = WasmGrammar::new(
	"protobuf",
	"proto",
	"protobuf-0b226f4132ac4493.wasm",
	"0b226f4132ac4493642b8df1fbeb7541c92e36e3fb152064ef662d072135b795",
	73836,
);

/// `tree-sitter-r` 1.3.0.
pub static R: WasmGrammar = WasmGrammar::new(
	"r",
	"r",
	"r-908227b85fae8f37.wasm",
	"908227b85fae8f37660f9991110349a2ce6ecde650549c8a72cda800caa5e948",
	484429,
);

/// `tree-sitter-ruby` 0.23.1.
pub static RUBY: WasmGrammar = WasmGrammar::new(
	"ruby",
	"ruby",
	"ruby-e77f88559b47c0fe.wasm",
	"e77f88559b47c0fe2771821c6c160cdf6bbfe17afcd642ab3fdda9aebb70b2f3",
	2106322,
);

/// `tree-sitter-scala` 0.26.2.
pub static SCALA: WasmGrammar = WasmGrammar::new(
	"scala",
	"scala",
	"scala-f1699072abf3668a.wasm",
	"f1699072abf3668a995ece3950a52c00f9da168a58684fe104e98214b0a74903",
	3922744,
);

/// `tree-sitter-solidity` 1.2.13.
pub static SOLIDITY: WasmGrammar = WasmGrammar::new(
	"solidity",
	"solidity",
	"solidity-ac4d44dc54b7a475.wasm",
	"ac4d44dc54b7a475c2284ae27ab0af932043e2cfd4e200a416b2ac5d40f433d7",
	508585,
);

/// `tree-sitter-sequel` 0.3.11.
pub static SQL: WasmGrammar = WasmGrammar::new(
	"sql",
	"sql",
	"sql-f9d5638965f6f7ec.wasm",
	"f9d5638965f6f7ecc6b6979b8717f44e756687a1cbe4fef411b84506bdb81451",
	2433442,
);

/// `tree-sitter-starlark` 1.3.0.
pub static STARLARK: WasmGrammar = WasmGrammar::new(
	"starlark",
	"starlark",
	"starlark-1f892a95b3d42e69.wasm",
	"1f892a95b3d42e69e71eeb3efdba3cc605a5c8b221b554e250f5418c64c682a6",
	329944,
);

/// `tree-sitter-svelte-next` 0.1.1.
pub static SVELTE: WasmGrammar = WasmGrammar::new(
	"svelte",
	"svelte",
	"svelte-03ab329192177443.wasm",
	"03ab329192177443c91eaf0904b011089cc6b779df1792468afd379c0a6a2512",
	44859,
);

/// `tree-sitter-swift` 0.7.3.
pub static SWIFT: WasmGrammar = WasmGrammar::new(
	"swift",
	"swift",
	"swift-92a6aa39712255e7.wasm",
	"92a6aa39712255e7332d1b06db52bc6d49e9f563215846978c0ca63b6cc38359",
	3726992,
);

/// `tree-sitter-tlaplus` 1.5.0.
pub static TLAPLUS: WasmGrammar = WasmGrammar::new(
	"tlaplus",
	"tlaplus",
	"tlaplus-2bb6711906017f86.wasm",
	"2bb6711906017f861d3c143553c5077fc167f29d023a606a5dcfc159efb9e5bc",
	4878580,
);

/// `tree-sitter-verilog` 1.0.3.
pub static VERILOG: WasmGrammar = WasmGrammar::new(
	"verilog",
	"verilog",
	"verilog-46f723039630ef85.wasm",
	"46f723039630ef85b8a2dd324cba2673207163f760eb435c800bc0f56d78bb0e",
	18135336,
);

/// `tree-sitter-vue-next` 0.1.0.
pub static VUE: WasmGrammar = WasmGrammar::new(
	"vue",
	"vue",
	"vue-a9b2b4573afa0f31.wasm",
	"a9b2b4573afa0f31a878753a30e2cda2030baa26544159448da6ba8c69bfa76d",
	28095,
);

/// `tree-sitter-xml` 0.7.0.
pub static XML: WasmGrammar = WasmGrammar::new(
	"xml",
	"xml",
	"xml-fafa7327c7a09ba7.wasm",
	"fafa7327c7a09ba74612e23543ff4e93ee08b785f0a8c2f8292c03f0b65c4917",
	46968,
);

/// `tree-sitter-zig` 1.1.2.
pub static ZIG: WasmGrammar = WasmGrammar::new(
	"zig",
	"zig",
	"zig-4dd568b541381b9d.wasm",
	"4dd568b541381b9ddcd0b53eda9956d26fea148b26f0af2ec52b1e8b4de3ed2e",
	691729,
);
