"""Repository rule detecting the Swift toolchain for the Apple Foundation Models bridge.

Runs `crates/pi-natives/src/applefm/build-bridge.sh detect` on the host and
materializes the result so the `applefm_bridge` genrule and link step see the
toolchain as an input:

    toolchain.txt   "<swiftc>\\t<sdk>\\t<fingerprint>", empty when no Swift 6.4+
                    toolchain with the macOS 27 SDK exists (the bridge is then
                    built from stub.c)
    defs.bzl        APPLEFM_LINKOPTS for the bridge's Swift runtime and weak
                    FoundationModels link (mirrors `applefm_link_args` in
                    crates/pi-natives/build.rs)

Caching: the fingerprint (compiler version + SDK build) is part of the
genrule's inputs, so action and remote caches never reuse a bridge built by a
different toolchain, and an unchanged toolchain never recompiles. The rule
re-runs when the selection env vars (tracked through `getenv`) or the watched
compiler/SDK files change, and on `bazel fetch --configure`.
"""

_ENV = ["OMP_APPLEFM_SWIFTC", "SDKROOT", "DEVELOPER_DIR"]

_CANDIDATE_SDK_SETTINGS = [
    "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/SDKSettings.plist",
]

def _watch_if_exists(rctx, path):
    if path and rctx.path(path).exists:
        rctx.watch(path)

def _applefm_swift_repository_impl(rctx):
    line = ""
    if rctx.os.name.lower().startswith("mac"):
        environment = {}
        for name in _ENV:
            value = rctx.getenv(name)
            if value:
                environment[name] = value
        script = rctx.path(Label("//crates/pi-natives:src/applefm/build-bridge.sh"))
        result = rctx.execute(["/bin/sh", str(script), "detect"], environment = environment)
        if result.return_code == 0:
            line = result.stdout.strip()
        selected = rctx.execute(["/usr/bin/xcrun", "--sdk", "macosx", "--show-sdk-path"])
        for settings in _CANDIDATE_SDK_SETTINGS + [selected.stdout.strip() + "/SDKSettings.plist"]:
            _watch_if_exists(rctx, settings)

    linkopts = []
    if line:
        swiftc, sdk, _fingerprint = line.split("\t")
        _watch_if_exists(rctx, swiftc)
        _watch_if_exists(rctx, sdk + "/SDKSettings.plist")
        toolchain_lib = str(rctx.path(swiftc).dirname.dirname) + "/lib/swift/macosx"
        linkopts = [
            "-L" + sdk + "/usr/lib/swift",
            "-L" + toolchain_lib,
            "-Wl,-rpath,/usr/lib/swift",
            "-Wl,-weak_library," + sdk + "/System/Library/Frameworks/FoundationModels.framework/FoundationModels.tbd",
        ]

    rctx.file("toolchain.txt", line + ("\n" if line else ""))
    rctx.file("defs.bzl", "APPLEFM_LINKOPTS = {}\n".format(repr(linkopts)))
    rctx.file("BUILD.bazel", """\
# Generated by //bazel/toolchains/swift:applefm.bzl.
exports_files(["toolchain.txt"], visibility = ["//visibility:public"])
""")

applefm_swift_repository = repository_rule(
    implementation = _applefm_swift_repository_impl,
    configure = True,
    doc = "Detects the Swift toolchain used to build the Apple Foundation Models bridge.",
)
