"""Repository rule fetching the swift.org Linux toolchain that cross-compiles the bridge.

Downloads the pinned Swift release for the linux host that fetches the repo
(the Ubuntu 22.04 build: glibc 2.35, and it runs unchanged on 24.04) and prunes
it to what `swiftc -emit-library` needs to compile and link
crates/pi-natives/src/applefm/bridge.swift for arm64-apple-macos against
@macos_sdk: swift-driver, swift-frontend, the clang it links through and the
host Swift runtime and compiler libraries those load (~900 MiB of ~4 GiB).

    darwin/clang   resource dir for darwin targets (-resource-dir darwin):
                   only the clang builtin headers. The default resource dir
                   (usr/lib/swift) also holds the Linux corelibs module maps
                   (CoreFoundation, dispatch, os, Block), which shadow the
                   SDK's frameworks once on the clang search path.

The open-source compiler builds the SDK's .swiftinterface files as long as its
version matches the one that generated them (Swift 6.4 for the macOS 27 SDK),
but unlike Apple's it does not put <sdk>/usr/lib/swift/shims on the clang
search path, so callers pass `-I <sdk>/usr/lib/swift/shims`; linking needs
`-ld-path` to an ld64.lld that reads the SDK's stubs (@llvm_darwin_tools).

Runtime dependencies on the host: libstdc++6, libsqlite3-0, libncurses6,
libuuid1, zlib1g (present on the Ubuntu runner images).

The ~1.1 GiB archive is sha256-pinned (repository cache) and the prune is
deterministic, so the repo opts into the repo contents cache.
"""

_VERSION = "6.4.0"

# host cpu -> (download dir suffix, archive suffix, sha256)
_DISTS = {
    "aarch64": ("ubuntu2204-aarch64", "ubuntu22.04-aarch64", "28c28acb2b91ed0e3beff5e6ba3695a785e645d9bd374adcaa3b7c2a901bc763"),
    "x86_64": ("ubuntu2204", "ubuntu22.04", "bce85ea80f1471b85f39993f9285dbc798ec8e1eac5f677e24b2ac693856f9f8"),
}

_KEEP_BINS = ["clang", "swift-driver", "swift-frontend", "swiftc"]

# usr/lib entries the compiler and driver do not load (debugger, SourceKit,
# indexing, static/embedded stdlibs, package manager).
_DROP_LIBS = [
    "libIndexStore.so",
    "libIndexStore.so.21.0",
    "libLTO.so",
    "libLTO.so.21.0",
    "libSwiftSourceKitClientPlugin.so",
    "libSwiftSourceKitPlugin.so",
    "libclang.so",
    "libclang.so.21.0",
    "libclang.so.21.0.0",
    "liblldb.so",
    "liblldb.so.21.0",
    "liblldb.so.21.0.0",
    "libsourcekitdInProc.so",
    "swift/FrameworkABIBaseline",
    "swift/embedded",
    "swift/migrator",
    "swift/pm",
    "swift_static",
]

_BUILD = """\
# Generated by //bazel/toolchains/swift:linux.bzl — pruned Swift {version} for
# the linux-hosted Apple Foundation Models bridge toolchain.

package(default_visibility = ["//visibility:public"])

exports_files(["usr/bin/swiftc"])

filegroup(
    name = "all",
    srcs = glob(["darwin/**", "usr/**"], exclude_directories = 1),
)
"""

def _cpu(rctx):
    arch = rctx.os.arch.lower()
    if arch in ("amd64", "x86_64", "x64"):
        return "x86_64"
    if arch in ("aarch64", "arm64"):
        return "aarch64"
    fail("bazel/toolchains/swift: no Swift toolchain pinned for host CPU " + rctx.os.arch)

def _swift_linux_impl(rctx):
    if not rctx.os.name.lower().startswith("linux"):
        fail("bazel/toolchains/swift: @swift_linux is for linux exec hosts; mac hosts use the Xcode toolchain (applefm.bzl)")
    folder, suffix, sha256 = _DISTS[_cpu(rctx)]
    prefix = "swift-{}-RELEASE-{}".format(_VERSION, suffix)
    rctx.report_progress("Downloading Swift {} ({}, ~1.1 GiB, repository-cache backed)".format(_VERSION, suffix))
    rctx.download_and_extract(
        url = "https://download.swift.org/swift-{v}-release/{folder}/swift-{v}-RELEASE/{prefix}.tar.gz".format(
            v = _VERSION,
            folder = folder,
            prefix = prefix,
        ),
        sha256 = sha256,
        stripPrefix = prefix,
    )

    keep = {}
    bin_dir = rctx.path("usr/bin")
    for name in _KEEP_BINS:
        tool = bin_dir.get_child(name)
        if not tool.exists:
            fail("bazel/toolchains/swift: Swift {} has no usr/bin/{}".format(_VERSION, name))
        keep[name] = None
        keep[tool.realpath.basename] = None
    for entry in bin_dir.readdir():
        if entry.basename not in keep:
            rctx.delete(entry)
    for name in _DROP_LIBS:
        rctx.delete("usr/lib/" + name)
    for entry in rctx.path("usr").readdir():
        if entry.basename not in ("bin", "lib"):
            rctx.delete(entry)

    # usr/lib/swift/clang -> ../clang/<major>: the builtin headers alone.
    # Relative, so the link survives the repo contents cache relocating the
    # repo (rctx.symlink writes absolute targets).
    result = rctx.execute(["/bin/sh", "-c", "mkdir darwin && ln -s ../usr/lib/swift/clang darwin/clang"])
    if result.return_code != 0:
        fail("bazel/toolchains/swift: creating the darwin resource dir failed: " + result.stderr)
    rctx.file("BUILD.bazel", _BUILD.format(version = _VERSION), executable = False)
    return rctx.repo_metadata(reproducible = True)

swift_linux_repository = repository_rule(
    implementation = _swift_linux_impl,
    doc = "Pruned swift.org Linux toolchain for cross-compiling the Apple Foundation Models bridge.",
)
