"""Repository rule generating the hermetic clang + ld64.lld macOS cc toolchain.

Linux exec hosts cross-compile the darwin addons with this toolchain; mac hosts
keep the host Xcode toolchain. Like @msvc_cc, the repo holds only cheap
generated files — wrapper scripts and the cc_toolchain BUILD — so iterating on
flags never invalidates the big @llvm_darwin_tools / @macos_sdk downloads.

Wrappers derive every path from $0 (execroot-relative sibling repos), so they
work from Bazel actions (cwd = execroot) and from build scripts, where
rules_rust ${pwd}-expands CC/AR to absolute paths and cc-rs/cmake spawn the
tools from other working directories:

    bin/clang      clang --target=<arch>-apple-macos against @macos_sdk, linking
    bin/clang++    through ld64.lld. -mlinker-version tells clang the linker
                   speaks ld64's -platform_version; MACOSX_DEPLOYMENT_TARGET
                   defaults the deployment target to the addon floor (12.0)
                   for the rare invocation that passes no -mmacosx-version-min.
    bin/ar         llvm-ar, or llvm-libtool-darwin for libtool-style arguments:
                   Bazel's macOS archiver flags are libtool's (-static -o), and
                   cc-rs drives $AR with ar's (cq, s). Named `ar` because
                   rules_rust hides any archiver named *libtool* from build
                   scripts.
    bin/ranlib, bin/nm, bin/objcopy, bin/strip, bin/ld   LLVM equivalents.

The feature/action config is rules_cc's own unix_cc_toolchain_config.bzl with
target_libc = "macosx" (macOS features: libtool archiving, -mmacosx-version-min
from --macos_minimum_os, -fobjc-link-runtime), copied into the repo exactly
like @local_config_cc does; the flag lists mirror what @local_config_cc
generates on mac hosts, so both hosts build the same addon.
"""

load(":sdk.bzl", "MACOS_SDK_DIR")

_ARCHES = {
    "arm64": {"cpu": "darwin_arm64", "triple": "arm64-apple-macos"},
    "x86_64": {"cpu": "darwin_x86_64", "triple": "x86_64-apple-macos"},
}

_CLANG_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/darwin:cc.bzl. {tool} for {triple} against
# the @macos_sdk SDK, linking with ld64.lld.
set -eu
execroot="$(cd "$(dirname "$0")/../../.." && pwd)"
llvm="$execroot/external/{llvm}"
MACOSX_DEPLOYMENT_TARGET="${{MACOSX_DEPLOYMENT_TARGET:-12.0}}"
export MACOSX_DEPLOYMENT_TARGET
exec "$llvm/bin/{tool}" \\
  --target={triple} \\
  -isysroot "$execroot/external/{sdk}/{sdk_dir}" \\
  -fuse-ld=lld \\
  "--ld-path=$llvm/bin/ld64.lld" \\
  -mlinker-version=907 \\
  -Wno-unused-command-line-argument \\
  "$@"
"""

_AR_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/darwin:cc.bzl. Static archiver: Bazel's
# macOS archive action passes libtool arguments, cc-rs passes ar ones.
set -eu
execroot="$(cd "$(dirname "$0")/../../.." && pwd)"
llvm="$execroot/external/{llvm}"
case "${{1:-}}" in
  -D|-static|-no_warning_for_no_symbols) exec "$llvm/bin/llvm-libtool-darwin" "$@" ;;
esac
exec "$llvm/bin/llvm-ar" "$@"
"""

_PASSTHROUGH_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/darwin:cc.bzl.
set -eu
execroot="$(cd "$(dirname "$0")/../../.." && pwd)"
exec "$execroot/external/{llvm}/bin/{tool}" "$@"
"""

_NOP_WRAPPER = """\
#!/bin/sh
# Generated by //bazel/toolchains/darwin:cc.bzl. Placeholder for tools the
# cross toolchain does not ship (gcov/objdump/dwp).
exit 0
"""

_BUILD = """\
# Generated by //bazel/toolchains/darwin:cc.bzl — hermetic clang + ld64.lld
# cc toolchain for {triple} from linux exec hosts. The toolchain() targets
# registering this live in //bazel/toolchains.

load("@rules_cc//cc/toolchains:cc_toolchain.bzl", "cc_toolchain")
load(":unix_cc_toolchain_config.bzl", "cc_toolchain_config")

package(default_visibility = ["//visibility:public"])

filegroup(name = "empty")

filegroup(
    name = "all_files",
    srcs = glob(["bin/*"]) + [
        "@llvm_darwin_tools//:all",
        "@macos_sdk//:cc",
    ],
)

cc_toolchain_config(
    name = "config",
    abi_libc_version = "darwin",
    abi_version = "darwin",
    compile_flags = [
        "-fstack-protector",
        "-Wall",
        "-Wthread-safety",
        "-Wself-assign",
        "-Wunused-but-set-parameter",
        "-Wno-free-nonheap-object",
        "-fcolor-diagnostics",
        "-fno-omit-frame-pointer",
    ],
    compiler = "clang",
    coverage_compile_flags = ["-fprofile-instr-generate", "-fcoverage-mapping"],
    coverage_link_flags = ["-fprofile-instr-generate"],
    cpu = "{cpu}",
    cxx_builtin_include_directories = [
        "external/{llvm}/lib/clang",
        "external/{sdk}/{sdk_dir}/usr/include",
        "external/{sdk}/{sdk_dir}/System/Library/Frameworks",
        "external/{sdk}/{sdk_dir}/System/Library/SubFrameworks",
    ],
    cxx_flags = ["-std=c++17"],
    dbg_compile_flags = ["-g"],
    host_system_name = "local",
    link_flags = ["-headerpad_max_install_names"],
    link_libs = [
        "-lc++",
        "-lm",
    ],
    opt_compile_flags = [
        "-g0",
        "-O2",
        "-D_FORTIFY_SOURCE=1",
        "-DNDEBUG",
        "-ffunction-sections",
        "-fdata-sections",
    ],
    opt_link_flags = ["-Wl,-dead_strip"],
    target_libc = "macosx",
    target_system_name = "{triple}",
    tool_paths = {{
        "ar": "bin/ar",
        "cpp": "bin/clang",
        "dwp": "bin/nop",
        "gcc": "bin/clang",
        "gcov": "bin/nop",
        "ld": "bin/ld",
        "nm": "bin/nm",
        "objcopy": "bin/objcopy",
        "objdump": "bin/nop",
        "strip": "bin/strip",
    }},
    toolchain_identifier = "darwin_cross_{arch}",
    unfiltered_compile_flags = [
        "-no-canonical-prefixes",
        "-Wno-builtin-macro-redefined",
        "-D__DATE__=\\"redacted\\"",
        "-D__TIMESTAMP__=\\"redacted\\"",
        "-D__TIME__=\\"redacted\\"",
    ],
)

cc_toolchain(
    name = "cc_toolchain",
    all_files = ":all_files",
    ar_files = ":all_files",
    as_files = ":all_files",
    compiler_files = ":all_files",
    dwp_files = ":empty",
    linker_files = ":all_files",
    objcopy_files = ":all_files",
    strip_files = ":all_files",
    supports_param_files = 1,
    toolchain_config = ":config",
    toolchain_identifier = "darwin_cross_{arch}",
)
"""

def _darwin_cc_impl(rctx):
    llvm = rctx.attr.llvm_repo.repo_name
    sdk = rctx.attr.sdk_repo.repo_name
    arch = rctx.attr.arch
    t = _ARCHES[arch]

    for tool in ("clang", "clang++"):
        rctx.file("bin/" + tool, _CLANG_WRAPPER.format(
            llvm = llvm,
            sdk = sdk,
            sdk_dir = MACOS_SDK_DIR,
            tool = tool,
            triple = t["triple"],
        ), executable = True)
    rctx.file("bin/ar", _AR_WRAPPER.format(llvm = llvm), executable = True)
    for name, tool in {
        "ld": "ld64.lld",
        "nm": "llvm-nm",
        "objcopy": "llvm-objcopy",
        "ranlib": "llvm-ranlib",
        "strip": "llvm-strip",
    }.items():
        rctx.file("bin/" + name, _PASSTHROUGH_WRAPPER.format(llvm = llvm, tool = tool), executable = True)
    rctx.file("bin/nop", _NOP_WRAPPER, executable = True)

    # The unix feature/action machinery, verbatim from the resolved rules_cc
    # (same mechanism @local_config_cc uses).
    rctx.template("unix_cc_toolchain_config.bzl", rctx.attr._config_bzl, executable = False)
    rctx.file("BUILD.bazel", _BUILD.format(
        arch = arch,
        cpu = t["cpu"],
        llvm = llvm,
        sdk = sdk,
        sdk_dir = MACOS_SDK_DIR,
        triple = t["triple"],
    ), executable = False)

darwin_cc_repository = repository_rule(
    implementation = _darwin_cc_impl,
    doc = "clang/ld64.lld wrapper scripts + macOS-flavored cc_toolchain for {arm64,x86_64}-apple-darwin.",
    attrs = {
        "arch": attr.string(
            mandatory = True,
            values = _ARCHES.keys(),
            doc = "Target CPU (arm64 or x86_64).",
        ),
        "llvm_repo": attr.label(
            default = "@llvm_darwin_tools//:BUILD.bazel",
            doc = "Anchor into the pruned LLVM tools repo (canonical name source; not fetched here).",
        ),
        "sdk_repo": attr.label(
            default = "@macos_sdk//:BUILD.bazel",
            doc = "Anchor into the macOS SDK repo (canonical name source; not fetched here).",
        ),
        "_config_bzl": attr.label(
            default = "@rules_cc//cc/private/toolchain:unix_cc_toolchain_config.bzl",
        ),
    },
)
