"""Repository rule materializing the macOS SDK from Apple's Command Line Tools.

Downloads the newest-SDK package of the Command Line Tools for Xcode 27.0
(`CLTools_macOSNMOS_SDK.pkg`) from Apple's software update CDN — the
unauthenticated catalog `softwareupdate` installs the Command Line Tools from —
and unpacks its MacOSX27.0.sdk with extract_pkg.py, so linux exec hosts get
the SDK straight from Apple, the way @xwin_sysroot gets the MSVC CRT from
Microsoft. Requires python3 on the exec host (standard library only).

    MacOSX27.0.sdk/   the SDK, minus its man pages, Mac Catalyst support
                      (System/iOSSupport) and Perl modules

The package download (~70 MiB) is sha256-pinned, so it lands in Bazel's
repository cache; extraction (~5 s) is a pure function of it, so the repo
opts into the repo contents cache.

Bumping: the catalog lists every Command Line Tools release; the product whose
`.dist` names "Command Line Tools for Xcode <version>" carries the package.

    curl -fsSL https://swscan.apple.com/content/catalogs/others/index-27-26-15-14-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog \\
      | grep -o 'https://swcdn[^<]*CLTools_macOSNMOS_SDK.pkg'

Update _URL, _SHA256 and _SDK together (the SDK directory name is printed by
extract_pkg.py's "no <member>" error when it changes).
"""

_URL = "https://swcdn.apple.com/content/downloads/58/48/082-83364-A_KCEBOO2NJS/0d2rj4y5ucjlkgcvqt6f6a4pergug5tu2b/CLTools_macOSNMOS_SDK.pkg"
_SHA256 = "d55351824fd17742fd6e1e7a252fa1028698f32147ee48be9a6b75442bf30575"
_SDK = "MacOSX27.0.sdk"
_EXCLUDES = [
    "System/iOSSupport",
    "System/Library/Perl",
    "usr/share/man",
]

_BUILD = """\
# Generated by //bazel/toolchains/darwin:sdk.bzl — {sdk} from the Command Line
# Tools package, for the linux-hosted darwin cc and Swift toolchains.

package(default_visibility = ["//visibility:public"])

# The SDK's settings file; its directory is the SDK root.
filegroup(
    name = "settings",
    srcs = ["{sdk}/SDKSettings.json"],
)

# Headers, .tbd stubs and frameworks: what C/ObjC compiles and links read.
filegroup(
    name = "cc",
    srcs = glob(
        ["{sdk}/**"],
        exclude = ["{sdk}/usr/lib/swift/**"],
        exclude_directories = 1,
    ),
)

# The Swift standard library and overlay interfaces, for swiftc.
filegroup(
    name = "swift",
    srcs = glob(["{sdk}/usr/lib/swift/**"], exclude_directories = 1),
)
"""

def _macos_sdk_impl(rctx):
    if not rctx.os.name.lower().startswith("linux"):
        fail("bazel/toolchains/darwin: @macos_sdk is for linux exec hosts; mac hosts build darwin targets with Xcode")
    python = rctx.which("python3")
    if not python:
        fail("bazel/toolchains/darwin: python3 is required on the exec host to unpack the macOS SDK")
    rctx.report_progress("Downloading the Command Line Tools macOS SDK package (~70 MiB, repository-cache backed)")
    rctx.download(url = _URL, output = "sdk.pkg", sha256 = _SHA256)
    rctx.report_progress("Unpacking " + _SDK)
    extractor = rctx.path(Label("//bazel/toolchains/darwin:extract_pkg.py"))
    rctx.watch(extractor)
    args = [
        python,
        extractor,
        "sdk.pkg",
        "Library/Developer/CommandLineTools/SDKs/" + _SDK,
        _SDK,
    ]
    for exclude in _EXCLUDES:
        args += ["--exclude", exclude]
    result = rctx.execute(args, timeout = 600)
    if result.return_code != 0:
        fail("bazel/toolchains/darwin: unpacking {} failed:\n{}{}".format(_SDK, result.stdout, result.stderr))
    rctx.delete("sdk.pkg")
    rctx.file("BUILD.bazel", _BUILD.format(sdk = _SDK), executable = False)
    return rctx.repo_metadata(reproducible = True)

macos_sdk_repository = repository_rule(
    implementation = _macos_sdk_impl,
    doc = "The macOS SDK unpacked from Apple's Command Line Tools package (linux exec hosts).",
)

MACOS_SDK_DIR = _SDK
