import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import type { Context, Model, ModelSpec, Tool } from "@oh-my-pi/pi-ai";
import { buildParams } from "@oh-my-pi/pi-ai/providers/openai-responses";
import { buildModel } from "@oh-my-pi/pi-catalog/build";
import { getBundledModel } from "@oh-my-pi/pi-catalog/models";
import { EditSession, EditStore, editDescription, type EditPolicy } from "@oh-my-pi/pi-natives";
import { type } from "@oh-my-pi/omptype";
import { editDescriptionCompact } from "../src/edit/index";

const WARMUP = 10;
const SAMPLES = 41;
const REQUEST_REPETITIONS = 100;
const root = path.join(os.tmpdir(), "omp-bench-muse-hashline");
const target = path.join(root, "fixture.ts");
const fixture =
	Array.from(
		{ length: 1_200 },
		(_, index) => `export const value${index + 1} = ${index + 1}; // deterministic hashline benchmark payload`,
	).join("\n") + "\n";
const replacement = "export const value600 = 600_000; // deterministic hashline benchmark payload";

// Resolve the real bundled muse-code catalog row, then re-resolve it through
// the live compat rules so KDL policy edits are measured without waiting for
// `bun run gen:models` to re-bake models.json.
const bundled = getBundledModel("muse-code", "muse-spark-1.3-contributor");
if (!bundled) throw new Error("muse-code/muse-spark-1.3-contributor missing from bundled catalog");
const model = buildModel(bundled as unknown as ModelSpec<"openai-responses">) as Model<"openai-responses">;
if (model.provider !== "muse-code") throw new Error(`unexpected provider: ${model.provider}`);
if (model.editPromptVariant !== "compact")
	throw new Error("muse-code catalog policy did not resolve edit-prompt-variant compact");
// The edit tool ships as a JSON function tool: Meta rejects freeform custom
// tools on this endpoint with 400, so apply-patch-tool-type is intentionally
// unset for muse-code. Assert the shipped configuration, not the removed one.
if (model.applyPatchToolType === "freeform")
	throw new Error("muse-code must not resolve freeform custom tools (Meta 400s type:custom)");

// Mirrors resolveEditToolDescription in src/edit/index.ts.
const editPrompt =
	model.editPromptVariant === "compact"
		? (editDescriptionCompact("hashline") ?? editDescription("hashline"))
		: editDescription("hashline");

const tools: Tool[] = [
	{
		name: "read",
		description: "Read a file or URL with line-addressable output.",
		parameters: type({ path: "string", "offset?": "number", "limit?": "number" }),
	},
	{
		name: "bash",
		description: "Run one binary or a short pipeline and capture its output.",
		parameters: type({ command: "string", "cwd?": "string", "timeout?": "number" }),
	},
	{
		name: "grep",
		description: "Search files using a regular expression.",
		parameters: type({ pattern: "string", "path?": "string", "case?": "boolean" }),
	},
	{
		name: "glob",
		description: "Match repository paths using glob patterns.",
		parameters: type({ "path?": "string", "limit?": "number" }),
	},
	{
		name: "edit",
		description: editPrompt,
		parameters: type({ input: "string" }),
	},
];

const context: Context = {
	systemPrompt: [
		"You are a precise coding agent. Inspect before editing, use hashline anchors, preserve project conventions, and verify behavioral changes.",
	],
	messages: [
		{
			role: "user",
			content: "Change value600 to 600000 in fixture.ts and keep the comment unchanged.",
			timestamp: 0,
		},
	],
	tools,
};

const policy: EditPolicy = {
	cwd: root,
	mode: "hashline",
	allowFuzzy: false,
	fuzzyThreshold: 1,
	enforceSeenLines: true,
	blockAutoGenerated: false,
	planActive: false,
	homeDir: os.homedir(),
	rawInput: false,
};

function median(values: number[]): number {
	const sorted = values.toSorted((left, right) => left - right);
	return sorted[Math.floor(sorted.length / 2)];
}

function buildRequest(): string {
	const { params } = buildParams(model, context, { reasoning: "high" }, undefined);
	return JSON.stringify(params);
}

async function applyHashlineEdit(): Promise<void> {
	await Bun.write(target, fixture);
	const store = new EditStore();
	const tag = store.recordSnapshot(target, fixture, [600]);
	const input = `*** Begin Patch\n[fixture.ts#${tag}]\nPUT 600.=600:\n+${replacement}\n*** End Patch\n`;
	const session = new EditSession(store, policy);
	try {
		session.setArgsJson(JSON.stringify({ input }));
		session.finish();
		const outcome = await session.apply({ lspFlush: false }, async (_error, request) => {
			if (request.op !== "update" || request.content === undefined) {
				throw new Error(`unexpected edit operation: ${request.op}`);
			}
			await Bun.write(request.path, request.content);
			return { written: request.content };
		});
		if (outcome.isError) throw new Error(outcome.text);
	} finally {
		session.close();
	}
	const edited = await Bun.file(target).text();
	if (!edited.includes(`${replacement}\n`)) throw new Error("hashline edit did not apply the expected replacement");
}

await fs.rm(root, { recursive: true, force: true });
await fs.mkdir(root, { recursive: true });
try {
	for (let index = 0; index < WARMUP; index++) {
		buildRequest();
		await applyHashlineEdit();
	}

	const requestSamples: number[] = [];
	const editSamples: number[] = [];
	let payload = "";
	for (let sample = 0; sample < SAMPLES; sample++) {
		let started = Bun.nanoseconds();
		for (let repetition = 0; repetition < REQUEST_REPETITIONS; repetition++) payload = buildRequest();
		requestSamples.push((Bun.nanoseconds() - started) / REQUEST_REPETITIONS / 1_000);

		started = Bun.nanoseconds();
		await applyHashlineEdit();
		editSamples.push((Bun.nanoseconds() - started) / 1_000);
	}

	const hashlineEditUs = median(editSamples);
	const requestBuildUs = median(requestSamples);
	const payloadBytes = Buffer.byteLength(payload);
	const toolSchemaBytes = Buffer.byteLength(JSON.stringify(JSON.parse(payload).tools ?? []));

	process.stdout.write(`METRIC hashline_edit_us=${hashlineEditUs.toFixed(3)}\n`);
	process.stdout.write(`METRIC muse_request_build_us=${requestBuildUs.toFixed(3)}\n`);
	process.stdout.write(`METRIC muse_payload_bytes=${payloadBytes}\n`);
	process.stdout.write(`METRIC muse_tool_schema_bytes=${toolSchemaBytes}\n`);
	process.stderr.write(
		`edit prompt: ${Buffer.byteLength(editPrompt)} bytes (full ${Buffer.byteLength(editDescription("hashline"))})\n`,
	);
} finally {
	await fs.rm(root, { recursive: true, force: true });
}
