import { loadNative } from "./loader-state.js";
import { adaptDesktopSession } from "./desktop-adapter.js";

/**
 * Native addon entrypoint.
 *
 * Hand-written surface area: one `loadNative()` call. Everything else in
 * this file (the surface-area `export const` block between MARKER_START
 * and MARKER_END) is rewritten by `packages/natives/scripts/gen-enums.ts`
 * after `napi build` regenerates `index.d.ts`.
 *
 * Loader logic lives in `./loader-state.js` so the pure helpers stay
 * unit-testable without triggering AVX2 detection or filesystem probes on
 * import. Types are auto-generated by napi-rs in `./index.d.ts`.
 */

const nativeBindings = loadNative();
// --- generated native exports (do not edit) ---
// classes
export const AudioCapture = nativeBindings.AudioCapture;
export const AudioPlayback = nativeBindings.AudioPlayback;
export const DesktopSession = adaptDesktopSession(nativeBindings.DesktopSession);
export const DiffStream = nativeBindings.DiffStream;
export const EditSession = nativeBindings.EditSession;
export const EditStore = nativeBindings.EditStore;
export const FileLock = nativeBindings.FileLock;
export const HighlightStream = nativeBindings.HighlightStream;
export const IwanTunnel = nativeBindings.IwanTunnel;
export const LiveWebRtcPeer = nativeBindings.LiveWebRtcPeer;
export const MacAppearanceObserver = nativeBindings.MacAppearanceObserver;
export const NativeOAuthCallback = nativeBindings.NativeOAuthCallback;
export const PowerAssertion = nativeBindings.PowerAssertion;
export const Process = nativeBindings.Process;
export const PtySession = nativeBindings.PtySession;
export const Shell = nativeBindings.Shell;
export const TtyWriter = nativeBindings.TtyWriter;
export const VcsGitRepo = nativeBindings.VcsGitRepo;
export const VcsJjWorkspace = nativeBindings.VcsJjWorkspace;
export const VcsRepo = nativeBindings.VcsRepo;

// functions
export const __ompInstallTokioRuntime = nativeBindings.__ompInstallTokioRuntime;
export const __piNativesV18_1_12 = nativeBindings.__piNativesV18_1_12;
export const astEdit = nativeBindings.astEdit;
export const astGrep = nativeBindings.astGrep;
export const astMatch = nativeBindings.astMatch;
export const blockRangeAt = nativeBindings.blockRangeAt;
export const copyToClipboard = nativeBindings.copyToClipboard;
export const cosineSimilarityPairs = nativeBindings.cosineSimilarityPairs;
export const countTokens = nativeBindings.countTokens;
export const decodeSixelToPng = nativeBindings.decodeSixelToPng;
export const detectMacOSAppearance = nativeBindings.detectMacOSAppearance;
export const deviceCheckGenerateToken = nativeBindings.deviceCheckGenerateToken;
export const diffLineRuns = nativeBindings.diffLineRuns;
export const diffLines = nativeBindings.diffLines;
export const diffWords = nativeBindings.diffWords;
export const editAutoGeneratedMessage = nativeBindings.editAutoGeneratedMessage;
export const editDescription = nativeBindings.editDescription;
export const editDiffString = nativeBindings.editDiffString;
export const editGrammar = nativeBindings.editGrammar;
export const editInspect = nativeBindings.editInspect;
export const enclosingBlockBoundaries = nativeBindings.enclosingBlockBoundaries;
export const encodeSixel = nativeBindings.encodeSixel;
export const execReplace = nativeBindings.execReplace;
export const executeShell = nativeBindings.executeShell;
export const extractInlineSloppyRegions = nativeBindings.extractInlineSloppyRegions;
export const extractSegments = nativeBindings.extractSegments;
export const fuzzyFind = nativeBindings.fuzzyFind;
export const getSupportedLanguages = nativeBindings.getSupportedLanguages;
export const getWorkProfile = nativeBindings.getWorkProfile;
export const glob = nativeBindings.glob;
export const grep = nativeBindings.grep;
export const hashlineCountOps = nativeBindings.hashlineCountOps;
export const hashlineFileHash = nativeBindings.hashlineFileHash;
export const hashlineFormatHeader = nativeBindings.hashlineFormatHeader;
export const hashlineFormatNumberedLines = nativeBindings.hashlineFormatNumberedLines;
export const hashlineStripPrefixes = nativeBindings.hashlineStripPrefixes;
export const hasMatch = nativeBindings.hasMatch;
export const highlightCode = nativeBindings.highlightCode;
export const htmlToMarkdown = nativeBindings.htmlToMarkdown;
export const invalidateFsScanCache = nativeBindings.invalidateFsScanCache;
export const isoBackend = nativeBindings.isoBackend;
export const isoDiff = nativeBindings.isoDiff;
export const isoIsUnavailableError = nativeBindings.isoIsUnavailableError;
export const isoProbe = nativeBindings.isoProbe;
export const isoResolve = nativeBindings.isoResolve;
export const isoStart = nativeBindings.isoStart;
export const isoStop = nativeBindings.isoStop;
export const listWorkspace = nativeBindings.listWorkspace;
export const macOSAutocorrectWord = nativeBindings.macOSAutocorrectWord;
export const macOSCheckSpelling = nativeBindings.macOSCheckSpelling;
export const macOSCompleteWord = nativeBindings.macOSCompleteWord;
export const macOSSpellCheckerAvailable = nativeBindings.macOSSpellCheckerAvailable;
export const macOSSpellingGuesses = nativeBindings.macOSSpellingGuesses;
export const matchesKey = nativeBindings.matchesKey;
export const matchesKittySequence = nativeBindings.matchesKittySequence;
export const matchesLegacySequence = nativeBindings.matchesLegacySequence;
export const mmrRerankIndices = nativeBindings.mmrRerankIndices;
export const nodeChainAt = nativeBindings.nodeChainAt;
export const notebookToEditableText = nativeBindings.notebookToEditableText;
export const parseKey = nativeBindings.parseKey;
export const parseKittySequence = nativeBindings.parseKittySequence;
export const pdfToMarkdown = nativeBindings.pdfToMarkdown;
export const rasterizeSvg = nativeBindings.rasterizeSvg;
export const readImageFromClipboard = nativeBindings.readImageFromClipboard;
export const renderSnapcompactPng = nativeBindings.renderSnapcompactPng;
export const search = nativeBindings.search;
export const setHangulCompatJamoWidthOverride = nativeBindings.setHangulCompatJamoWidthOverride;
export const sliceWithWidth = nativeBindings.sliceWithWidth;
export const snapcompactSupportedChars = nativeBindings.snapcompactSupportedChars;
export const structuredPatchHunks = nativeBindings.structuredPatchHunks;
export const summarizeCode = nativeBindings.summarizeCode;
export const supportsLanguage = nativeBindings.supportsLanguage;
export const truncateToWidth = nativeBindings.truncateToWidth;
export const vcsDetachGitDir = nativeBindings.vcsDetachGitDir;
export const vcsDiscover = nativeBindings.vcsDiscover;
export const vcsGitClone = nativeBindings.vcsGitClone;
export const vcsGitDiscover = nativeBindings.vcsGitDiscover;
export const vcsGitRepoInfo = nativeBindings.vcsGitRepoInfo;
export const vcsIsPureJj = nativeBindings.vcsIsPureJj;
export const vcsJjDiscover = nativeBindings.vcsJjDiscover;
export const vcsJoinPatches = nativeBindings.vcsJoinPatches;
export const vcsValidateHunkSelections = nativeBindings.vcsValidateHunkSelections;
export const vectorIndexTopK = nativeBindings.vectorIndexTopK;
export const visibleWidth = nativeBindings.visibleWidth;
export const warmHighlighter = nativeBindings.warmHighlighter;
export const wrapTextWithAnsi = nativeBindings.wrapTextWithAnsi;

// string/numeric enums (napi-rs string_enum produces TS-only const enum)
export const AstMatchStrictness = {
	Cst: "cst",
	Smart: "smart",
	Ast: "ast",
	Relaxed: "relaxed",
	Signature: "signature",
	Template: "template",
};
export const DiffSide = {
	Old: "Old",
	New: "New",
};
export const Ellipsis = {
	Unicode: 0,
	Ascii: 1,
	Omit: 2,
};
export const Encoding = {
	O200kBase: "O200kBase",
	Cl100kBase: "Cl100kBase",
	ClaudeV3: "ClaudeV3",
	ClaudeV47: "ClaudeV47",
	ClaudeV5: "ClaudeV5",
	ClaudeV5Sonnet: "ClaudeV5Sonnet",
	Qwen3: "Qwen3",
	DeepSeekV3: "DeepSeekV3",
	KimiK2: "KimiK2",
	Glm5: "Glm5",
};
export const FileType = {
	File: 1,
	Dir: 2,
	Symlink: 3,
};
export const GrepOutputMode = {
	Content: "content",
	Count: "count",
	FilesWithMatches: "filesWithMatches",
};
export const IsoBackendKind = {
	Apfs: 0,
	Btrfs: 1,
	Zfs: 2,
	LinuxReflink: 3,
	Overlayfs: 4,
	WindowsBlockClone: 5,
	Projfs: 6,
	Rcopy: 7,
};
export const IsoChangeKind = {
	Added: 0,
	Modified: 1,
	Removed: 2,
};
export const KeyEventType = {
	Press: 1,
	Repeat: 2,
	Release: 3,
};
export const MacOSAppearance = {
	Dark: "dark",
	Light: "light",
};
export const ProcessStatus = {
	Running: "running",
	Exited: "exited",
};
// --- end generated native exports ---
