import { loadNative, missingNativeExport } from "./loader-state.js";
import { adaptDesktopSession } from "./desktop-adapter.js";

/**
 * Native addon entrypoint.
 *
 * Hand-written surface area: one `loadNative()` call. Everything else in
 * this file (the surface-area `export const` block between MARKER_START
 * and MARKER_END) is rewritten by `packages/natives/scripts/gen-enums.ts`
 * after `napi build` regenerates `index.d.ts`.
 *
 * Loader logic lives in `./loader-state.js` so the pure helpers stay
 * unit-testable without triggering AVX2 detection or filesystem probes on
 * import. Types are auto-generated by napi-rs in `./index.d.ts`.
 *
 * Function exports fall back to `missingNativeExport` instead of a bare
 * `undefined`: a workspace tree that pulled a new release loads its previous
 * addon by design (see `validateLoadedBindings`), and every symbol added since
 * that build would otherwise fail as `<symbol> is not a function` inside
 * whichever tool used it first.
 */

const nativeBindings = loadNative();
// --- generated native exports (do not edit) ---
// classes
export const AudioCapture = nativeBindings.AudioCapture;
export const AudioPlayback = nativeBindings.AudioPlayback;
export const DesktopSession = adaptDesktopSession(nativeBindings.DesktopSession);
export const DiffStream = nativeBindings.DiffStream;
export const EditSession = nativeBindings.EditSession;
export const EditStore = nativeBindings.EditStore;
export const FileLock = nativeBindings.FileLock;
export const HighlightStream = nativeBindings.HighlightStream;
export const IwanTunnel = nativeBindings.IwanTunnel;
export const LiveWebRtcPeer = nativeBindings.LiveWebRtcPeer;
export const MacAppearanceObserver = nativeBindings.MacAppearanceObserver;
export const NativeOAuthCallback = nativeBindings.NativeOAuthCallback;
export const PowerAssertion = nativeBindings.PowerAssertion;
export const Process = nativeBindings.Process;
export const PtySession = nativeBindings.PtySession;
export const Shell = nativeBindings.Shell;
export const TtyWriter = nativeBindings.TtyWriter;
export const VcsGitRepo = nativeBindings.VcsGitRepo;
export const VcsJjWorkspace = nativeBindings.VcsJjWorkspace;
export const VcsRepo = nativeBindings.VcsRepo;

// functions
export const __ompInstallTokioRuntime = nativeBindings.__ompInstallTokioRuntime ?? missingNativeExport("__ompInstallTokioRuntime");
export const __piNativesV18_2_11 = nativeBindings.__piNativesV18_2_11;
export const astEdit = nativeBindings.astEdit ?? missingNativeExport("astEdit");
export const astGrep = nativeBindings.astGrep ?? missingNativeExport("astGrep");
export const astMatch = nativeBindings.astMatch ?? missingNativeExport("astMatch");
export const blockRangeAt = nativeBindings.blockRangeAt ?? missingNativeExport("blockRangeAt");
export const copyToClipboard = nativeBindings.copyToClipboard ?? missingNativeExport("copyToClipboard");
export const cosineSimilarityPairs = nativeBindings.cosineSimilarityPairs ?? missingNativeExport("cosineSimilarityPairs");
export const countTokens = nativeBindings.countTokens ?? missingNativeExport("countTokens");
export const decodeSixelToPng = nativeBindings.decodeSixelToPng ?? missingNativeExport("decodeSixelToPng");
export const detectMacOSAppearance = nativeBindings.detectMacOSAppearance ?? missingNativeExport("detectMacOSAppearance");
export const deviceCheckGenerateToken = nativeBindings.deviceCheckGenerateToken ?? missingNativeExport("deviceCheckGenerateToken");
export const diffLineRuns = nativeBindings.diffLineRuns ?? missingNativeExport("diffLineRuns");
export const diffLines = nativeBindings.diffLines ?? missingNativeExport("diffLines");
export const diffWords = nativeBindings.diffWords ?? missingNativeExport("diffWords");
export const editAutoGeneratedMessage = nativeBindings.editAutoGeneratedMessage ?? missingNativeExport("editAutoGeneratedMessage");
export const editDescription = nativeBindings.editDescription ?? missingNativeExport("editDescription");
export const editDiffString = nativeBindings.editDiffString ?? missingNativeExport("editDiffString");
export const editGrammar = nativeBindings.editGrammar ?? missingNativeExport("editGrammar");
export const editInspect = nativeBindings.editInspect ?? missingNativeExport("editInspect");
export const enclosingBlockBoundaries = nativeBindings.enclosingBlockBoundaries ?? missingNativeExport("enclosingBlockBoundaries");
export const encodeSixel = nativeBindings.encodeSixel ?? missingNativeExport("encodeSixel");
export const execReplace = nativeBindings.execReplace ?? missingNativeExport("execReplace");
export const executeShell = nativeBindings.executeShell ?? missingNativeExport("executeShell");
export const extractInlineSloppyRegions = nativeBindings.extractInlineSloppyRegions ?? missingNativeExport("extractInlineSloppyRegions");
export const extractSegments = nativeBindings.extractSegments ?? missingNativeExport("extractSegments");
export const fuzzyFind = nativeBindings.fuzzyFind ?? missingNativeExport("fuzzyFind");
export const getSupportedLanguages = nativeBindings.getSupportedLanguages ?? missingNativeExport("getSupportedLanguages");
export const getWorkProfile = nativeBindings.getWorkProfile ?? missingNativeExport("getWorkProfile");
export const glob = nativeBindings.glob ?? missingNativeExport("glob");
export const grep = nativeBindings.grep ?? missingNativeExport("grep");
export const hashlineCountOps = nativeBindings.hashlineCountOps ?? missingNativeExport("hashlineCountOps");
export const hashlineFileHash = nativeBindings.hashlineFileHash ?? missingNativeExport("hashlineFileHash");
export const hashlineFormatHeader = nativeBindings.hashlineFormatHeader ?? missingNativeExport("hashlineFormatHeader");
export const hashlineFormatNumberedLines = nativeBindings.hashlineFormatNumberedLines ?? missingNativeExport("hashlineFormatNumberedLines");
export const hashlineIsReadTruncationNotice = nativeBindings.hashlineIsReadTruncationNotice ?? missingNativeExport("hashlineIsReadTruncationNotice");
export const hashlineStripPrefixes = nativeBindings.hashlineStripPrefixes ?? missingNativeExport("hashlineStripPrefixes");
export const hasMatch = nativeBindings.hasMatch ?? missingNativeExport("hasMatch");
export const highlightCode = nativeBindings.highlightCode ?? missingNativeExport("highlightCode");
export const htmlToMarkdown = nativeBindings.htmlToMarkdown ?? missingNativeExport("htmlToMarkdown");
export const invalidateFsScanCache = nativeBindings.invalidateFsScanCache ?? missingNativeExport("invalidateFsScanCache");
export const isoBackend = nativeBindings.isoBackend ?? missingNativeExport("isoBackend");
export const isoDiff = nativeBindings.isoDiff ?? missingNativeExport("isoDiff");
export const isoIsUnavailableError = nativeBindings.isoIsUnavailableError ?? missingNativeExport("isoIsUnavailableError");
export const isoProbe = nativeBindings.isoProbe ?? missingNativeExport("isoProbe");
export const isoResolve = nativeBindings.isoResolve ?? missingNativeExport("isoResolve");
export const isoStart = nativeBindings.isoStart ?? missingNativeExport("isoStart");
export const isoStop = nativeBindings.isoStop ?? missingNativeExport("isoStop");
export const listWorkspace = nativeBindings.listWorkspace ?? missingNativeExport("listWorkspace");
export const macOSAutocorrectWord = nativeBindings.macOSAutocorrectWord ?? missingNativeExport("macOSAutocorrectWord");
export const macOSCheckSpelling = nativeBindings.macOSCheckSpelling ?? missingNativeExport("macOSCheckSpelling");
export const macOSCompleteWord = nativeBindings.macOSCompleteWord ?? missingNativeExport("macOSCompleteWord");
export const macOSSpellCheckerAvailable = nativeBindings.macOSSpellCheckerAvailable ?? missingNativeExport("macOSSpellCheckerAvailable");
export const macOSSpellingGuesses = nativeBindings.macOSSpellingGuesses ?? missingNativeExport("macOSSpellingGuesses");
export const matchesKey = nativeBindings.matchesKey ?? missingNativeExport("matchesKey");
export const matchesKittySequence = nativeBindings.matchesKittySequence ?? missingNativeExport("matchesKittySequence");
export const matchesLegacySequence = nativeBindings.matchesLegacySequence ?? missingNativeExport("matchesLegacySequence");
export const mmrRerankIndices = nativeBindings.mmrRerankIndices ?? missingNativeExport("mmrRerankIndices");
export const nodeChainAt = nativeBindings.nodeChainAt ?? missingNativeExport("nodeChainAt");
export const notebookToEditableText = nativeBindings.notebookToEditableText ?? missingNativeExport("notebookToEditableText");
export const parseKey = nativeBindings.parseKey ?? missingNativeExport("parseKey");
export const parseKittySequence = nativeBindings.parseKittySequence ?? missingNativeExport("parseKittySequence");
export const pdfToMarkdown = nativeBindings.pdfToMarkdown ?? missingNativeExport("pdfToMarkdown");
export const rasterizeSvg = nativeBindings.rasterizeSvg ?? missingNativeExport("rasterizeSvg");
export const readImageFromClipboard = nativeBindings.readImageFromClipboard ?? missingNativeExport("readImageFromClipboard");
export const renderMermaidAscii = nativeBindings.renderMermaidAscii ?? missingNativeExport("renderMermaidAscii");
export const renderSnapcompactPng = nativeBindings.renderSnapcompactPng ?? missingNativeExport("renderSnapcompactPng");
export const search = nativeBindings.search ?? missingNativeExport("search");
export const setHangulCompatJamoWidthOverride = nativeBindings.setHangulCompatJamoWidthOverride ?? missingNativeExport("setHangulCompatJamoWidthOverride");
export const sliceWithWidth = nativeBindings.sliceWithWidth ?? missingNativeExport("sliceWithWidth");
export const snapcompactSupportedChars = nativeBindings.snapcompactSupportedChars ?? missingNativeExport("snapcompactSupportedChars");
export const structuredPatchHunks = nativeBindings.structuredPatchHunks ?? missingNativeExport("structuredPatchHunks");
export const summarizeCode = nativeBindings.summarizeCode ?? missingNativeExport("summarizeCode");
export const supportsLanguage = nativeBindings.supportsLanguage ?? missingNativeExport("supportsLanguage");
export const truncateToWidth = nativeBindings.truncateToWidth ?? missingNativeExport("truncateToWidth");
export const vcsDetachGitDir = nativeBindings.vcsDetachGitDir ?? missingNativeExport("vcsDetachGitDir");
export const vcsDiscover = nativeBindings.vcsDiscover ?? missingNativeExport("vcsDiscover");
export const vcsDiscoverForDisplay = nativeBindings.vcsDiscoverForDisplay ?? missingNativeExport("vcsDiscoverForDisplay");
export const vcsGitClone = nativeBindings.vcsGitClone ?? missingNativeExport("vcsGitClone");
export const vcsGitDiscover = nativeBindings.vcsGitDiscover ?? missingNativeExport("vcsGitDiscover");
export const vcsGitRepoInfo = nativeBindings.vcsGitRepoInfo ?? missingNativeExport("vcsGitRepoInfo");
export const vcsIsPureJj = nativeBindings.vcsIsPureJj ?? missingNativeExport("vcsIsPureJj");
export const vcsJjDiscover = nativeBindings.vcsJjDiscover ?? missingNativeExport("vcsJjDiscover");
export const vcsJoinPatches = nativeBindings.vcsJoinPatches ?? missingNativeExport("vcsJoinPatches");
export const vcsValidateHunkSelections = nativeBindings.vcsValidateHunkSelections ?? missingNativeExport("vcsValidateHunkSelections");
export const vectorIndexTopK = nativeBindings.vectorIndexTopK ?? missingNativeExport("vectorIndexTopK");
export const visibleWidth = nativeBindings.visibleWidth ?? missingNativeExport("visibleWidth");
export const warmHighlighter = nativeBindings.warmHighlighter ?? missingNativeExport("warmHighlighter");
export const wrapTextWithAnsi = nativeBindings.wrapTextWithAnsi ?? missingNativeExport("wrapTextWithAnsi");

// string/numeric enums (napi-rs string_enum produces TS-only const enum)
export const AstMatchStrictness = {
	Cst: "cst",
	Smart: "smart",
	Ast: "ast",
	Relaxed: "relaxed",
	Signature: "signature",
	Template: "template",
};
export const DiffSide = {
	Old: "Old",
	New: "New",
};
export const Ellipsis = {
	Unicode: 0,
	Ascii: 1,
	Omit: 2,
};
export const Encoding = {
	O200kBase: "O200kBase",
	Cl100kBase: "Cl100kBase",
	ClaudeV3: "ClaudeV3",
	ClaudeV47: "ClaudeV47",
	ClaudeV5: "ClaudeV5",
	ClaudeV5Sonnet: "ClaudeV5Sonnet",
	Qwen3: "Qwen3",
	DeepSeekV3: "DeepSeekV3",
	KimiK2: "KimiK2",
	Glm5: "Glm5",
};
export const FileType = {
	File: 1,
	Dir: 2,
	Symlink: 3,
};
export const GrepOutputMode = {
	Content: "content",
	Count: "count",
	FilesWithMatches: "filesWithMatches",
};
export const IsoBackendKind = {
	Apfs: 0,
	Btrfs: 1,
	Zfs: 2,
	LinuxReflink: 3,
	Overlayfs: 4,
	WindowsBlockClone: 5,
	Projfs: 6,
	Rcopy: 7,
};
export const IsoChangeKind = {
	Added: 0,
	Modified: 1,
	Removed: 2,
};
export const KeyEventType = {
	Press: 1,
	Repeat: 2,
	Release: 3,
};
export const MacOSAppearance = {
	Dark: "dark",
	Light: "light",
};
export const ProcessStatus = {
	Running: "running",
	Exited: "exited",
};
// --- end generated native exports ---
