import { editAutoGeneratedMessage } from "@oh-my-pi/pi-natives";
import { settings as globalSettings, isSettingsInitialized, type Settings } from "../config/settings";
import { getDefault } from "../config/settings-schema";
import { ToolError } from "./tool-errors";

function shouldBlockAutoGeneratedFiles(activeSettings?: Settings): boolean {
	if (activeSettings) return activeSettings.get("edit.blockAutoGenerated");
	if (isSettingsInitialized()) return globalSettings.get("edit.blockAutoGenerated");
	return getDefault("edit.blockAutoGenerated");
}

/** Throw when the native generated-file detector rejects this path. */
export async function assertEditableFile(
	absolutePath: string,
	displayPath?: string,
	activeSettings?: Settings,
): Promise<void> {
	if (!shouldBlockAutoGeneratedFiles(activeSettings)) return;
	const message = editAutoGeneratedMessage(absolutePath, displayPath ?? absolutePath);
	if (message) throw new ToolError(message);
}
