"""Repository rule materializing the MSVC CRT + Windows SDK sysroot via xwin.

Downloads a pinned xwin release binary (github.com/Jake-Shadle/xwin) for the
host that fetches the repo and runs `xwin --accept-license splat`, producing:

    splat/crt/include             VC toolset headers
    splat/crt/lib/x86_64          VC toolset libs (msvcrt.lib & co)
    splat/sdk/include/{ucrt,um,shared,winrt,cppwinrt}
    splat/sdk/lib/{ucrt,um}/x86_64

Cache implications: only the small xwin binary tarball goes through Bazel's
repository cache. The CRT/SDK payload (~1 GiB) is downloaded from the
Microsoft CDN by xwin itself inside this rule, so a cold fetch (clean
--expunge, sysroot.bzl edit, new output base) re-downloads it. The xwin
download cache is deleted after splatting to keep the repo at ~800 MiB.
Keep this file stable; wrapper/toolchain iteration lives in cc.bzl precisely
so it never invalidates this repo.

Reproducibility: --manifest-version pins the VS channel (17 = VS2022), but
Microsoft advances the channel's payload over time, so the splat is stable
day-to-day, not bit-reproducible forever — same property the cargo-xwin
pipeline had.

xwin release binaries stop shipping darwin builds after 0.6.5; 0.6.5 is the
newest version covering linux-musl + darwin hosts, which is why it is pinned.
"""

_XWIN_VERSION = "0.6.5"
_XWIN_MANIFEST_VERSION = "17"

# host key -> (release triple, sha256), from the published .sha256 assets.
_XWIN_DISTS = {
    "linux-arm64": ("aarch64-unknown-linux-musl", "5e131007fad7c5f30d2f41090b49937fb8f16a787e5a95b4b3140e88d174dab2"),
    "linux-x64": ("x86_64-unknown-linux-musl", "9fd53950b064d067f42428a69453b927656cae68dbd7f8d3f86dcb81c80dd22d"),
    "macos-arm64": ("aarch64-apple-darwin", "21acd1e35d23b72efc8c47cbeda5028989f98089174b8c87074f892b65adbc01"),
    "macos-x64": ("x86_64-apple-darwin", "ecb2b19b30fa3786749fae600ad60b034b0c1c6a604ecf9f35f682c23a40e54b"),
}

def _host_key(rctx):
    os_name = rctx.os.name.lower()
    arch = rctx.os.arch.lower()
    if os_name.startswith("linux"):
        host_os = "linux"
    elif os_name.startswith("mac") or os_name.startswith("darwin"):
        host_os = "macos"
    else:
        fail("bazel/toolchains/msvc: unsupported exec host OS for xwin: " + rctx.os.name)
    if arch in ("amd64", "x86_64", "x64"):
        host_cpu = "x64"
    elif arch in ("aarch64", "arm64"):
        host_cpu = "arm64"
    else:
        fail("bazel/toolchains/msvc: unsupported exec host CPU for xwin: " + rctx.os.arch)
    return host_os + "-" + host_cpu

_BUILD = """\
# Generated by //bazel/toolchains/msvc:sysroot.bzl — MSVC CRT + Windows SDK
# splatted by xwin {version} (manifest-version {manifest}). Consumed by the
# @msvc_cc wrappers via /imsvc and /libpath.

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "crt_includes",
    srcs = glob(["splat/crt/include/**"]),
)

filegroup(
    name = "crt_libs",
    srcs = glob(["splat/crt/lib/**"]),
)

filegroup(
    name = "sdk_includes",
    srcs = glob(["splat/sdk/include/**"]),
)

filegroup(
    name = "sdk_libs",
    srcs = glob(["splat/sdk/lib/**"]),
)

filegroup(
    name = "sysroot",
    srcs = [
        ":crt_includes",
        ":crt_libs",
        ":sdk_includes",
        ":sdk_libs",
    ],
)
"""

def _xwin_sysroot_impl(rctx):
    key = _host_key(rctx)
    if key not in _XWIN_DISTS:
        fail("bazel/toolchains/msvc: no pinned xwin release binary for host " + key)
    triple, sha256 = _XWIN_DISTS[key]
    prefix = "xwin-{}-{}".format(_XWIN_VERSION, triple)
    rctx.download_and_extract(
        url = "https://github.com/Jake-Shadle/xwin/releases/download/{}/{}.tar.gz".format(_XWIN_VERSION, prefix),
        sha256 = sha256,
        stripPrefix = prefix,
    )
    rctx.report_progress("Splatting MSVC CRT + Windows SDK via xwin (first fetch ~1 GiB from the Microsoft CDN)")

    # OMP_XWIN_CACHE_DIR points at a persistent location (CI: the runner-cache
    # PVC via --repo_env) so ephemeral pods reuse the ~1 GiB CDN download the
    # repository cache cannot hold. Unset (dev machines): a repo-local cache,
    # deleted after the --copy splat.
    cache_dir = rctx.os.environ.get("OMP_XWIN_CACHE_DIR", "")
    ephemeral_cache = cache_dir == ""
    if ephemeral_cache:
        cache_dir = ".xwin-cache"

    result = rctx.execute(
        [
            rctx.path("xwin"),
            "--accept-license",
            "--arch",
            rctx.attr.arch,
            "--variant",
            "desktop",
            "--manifest-version",
            _XWIN_MANIFEST_VERSION,
        ] + (["--sdk-version", rctx.attr.sdk_version] if rctx.attr.sdk_version else []) + [
            "--cache-dir",
            cache_dir,
            "splat",
            "--copy",
            "--output",
            "splat",
        ],
        timeout = 3600,
    )
    if result.return_code != 0:
        fail("bazel/toolchains/msvc: xwin splat failed (exit {}):\n{}\n{}".format(
            result.return_code,
            result.stdout,
            result.stderr,
        ))

    # Drop the download cache (the splat is a --copy, not links into it).
    if ephemeral_cache:
        rctx.delete(cache_dir)

    # xwin drops `<sdk-version> -> .` alias symlinks (e.g. sdk/lib/10.0.26100)
    # so version-qualified include/lib paths resolve. They are self-referential
    # directory cycles, which Bazel's glob refuses to traverse — and nothing in
    # this toolchain uses version-qualified paths, so drop them.
    for dirname in ("splat/sdk/include", "splat/sdk/lib", "splat/crt/lib", "splat/crt/include"):
        dirpath = rctx.path(dirname)
        if not dirpath.exists:
            continue
        for entry in dirpath.readdir():
            if entry.realpath == dirpath.realpath:
                rctx.delete(entry)

    rctx.file(
        "BUILD.bazel",
        _BUILD.format(version = _XWIN_VERSION, manifest = _XWIN_MANIFEST_VERSION),
        executable = False,
    )

    # Opt into the repo contents cache. The splat is channel-stable, not
    # bit-reproducible forever (see the module docstring) — caching freezes a
    # known-good splat, which also keeps remote action keys stable across
    # pods until this file changes or the cache entry ages out (14 d GC).
    # OMP_XWIN_CACHE_DIR is a predeclared input (environ attr), so kata and
    # dev fetches key separate entries.
    return rctx.repo_metadata(reproducible = True)

xwin_sysroot_repository = repository_rule(
    implementation = _xwin_sysroot_impl,
    doc = "MSVC CRT + Windows SDK sysroot splatted by a pinned xwin release.",
    attrs = {
        # One repo per arch (not --arch x86_64,aarch64 in one splat) so the
        # x64 repo's splat and cache entry are unaffected by the arm64 target.
        "arch": attr.string(
            default = "x86_64",
            values = ["x86_64", "aarch64"],
            doc = "xwin --arch: target CRT/SDK library architecture.",
        ),
        # The newest SDK's arm64 MSIs reference no cab files, which xwin 0.6.5
        # rejects ("no cab files were referenced by the MSI", Jake-Shadle/xwin#126);
        # the arm64 splat pins an older SDK. Empty = xwin's default (latest).
        "sdk_version": attr.string(
            default = "",
            doc = "xwin --sdk-version override (e.g. 10.0.22621).",
        ),
    },
    # Persistent splat cache location; changing it only changes where the CDN
    # payload lands, not the splat contents, but Bazel still refetches.
    environ = ["OMP_XWIN_CACHE_DIR"],
)
