"""Repository rules fetching pruned LLVM release binaries for the cross toolchains.

Each rule downloads the official LLVM release archive for the host that
fetches the repo and prunes it to the `bin/` entries its toolchain wraps plus
the clang builtin headers (lib/clang/<major>/include — immintrin.h & co). The
pruned trees are a few hundred MiB instead of ~10 GiB.

    llvm_msvc_tools_repository    LLVM 20.1.7, clang-cl / lld-link / llvm-lib /
                                  llvm-rc for //bazel/toolchains/msvc (linux
                                  and mac exec hosts)
    llvm_darwin_tools_repository  LLVM 23.1.3, clang / ld64.lld / llvm-ar /
                                  llvm-libtool-darwin for
                                  //bazel/toolchains/darwin (linux exec hosts).
                                  23.1.3 is the first release whose ld64.lld
                                  reads the arm64e.x1 targets in the macOS 27
                                  SDK's .tbd stubs (llvm/llvm-project#222721);
                                  older ones reject libSystem.tbd outright.

Archive downloads (~1.5-2 GiB) go through repository_ctx.download_and_extract
with a pinned sha256, so they land in Bazel's content-addressed repository
cache: re-fetches after `bazel clean --expunge` or a .bzl edit only pay
extraction. Checksums are the official llvm-project release assets.
"""

def _host_key(rctx):
    os_name = rctx.os.name.lower()
    arch = rctx.os.arch.lower()
    if os_name.startswith("linux"):
        host_os = "linux"
    elif os_name.startswith("mac") or os_name.startswith("darwin"):
        host_os = "macos"
    else:
        fail("bazel/toolchains/llvm.bzl: unsupported exec host OS: " + rctx.os.name)
    if arch in ("amd64", "x86_64", "x64"):
        host_cpu = "x64"
    elif arch in ("aarch64", "arm64"):
        host_cpu = "arm64"
    else:
        fail("bazel/toolchains/llvm.bzl: unsupported exec host CPU: " + rctx.os.arch)
    return host_os + "-" + host_cpu

_BUILD = """\
# Generated by //bazel/toolchains:llvm.bzl — pruned LLVM {version} ({host} exec
# host). Consumed by the //bazel/toolchains/{consumer} wrappers.

package(default_visibility = ["//visibility:public"])

exports_files(glob(["bin/*"]))

filegroup(
    name = "bin",
    srcs = glob(["bin/*"]),
)

filegroup(
    name = "builtin_headers",
    srcs = glob(["lib/clang/*/include/**"]),
)

filegroup(
    name = "all",
    srcs = [
        ":bin",
        ":builtin_headers",
    ],
)
"""

def _llvm_tools_impl(rctx):
    key = _host_key(rctx)
    dist = rctx.attr.dists.get(key)
    if not dist:
        fail("bazel/toolchains/llvm.bzl: no pinned LLVM {} archive for {} hosts (the {} toolchain supports {})".format(
            rctx.attr.version,
            key,
            rctx.attr.consumer,
            ", ".join(rctx.attr.dists.keys()),
        ))
    suffix, sha256 = dist
    prefix = "LLVM-{}-{}".format(rctx.attr.version, suffix)
    rctx.report_progress("Downloading LLVM {} ({}, ~2 GiB, repository-cache backed)".format(rctx.attr.version, suffix))
    rctx.download_and_extract(
        url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-{}/{}.tar.xz".format(rctx.attr.version, prefix),
        sha256 = sha256,
        stripPrefix = prefix,
    )

    # Close the keep-set over symlink targets (clang-cl -> clang -> clang-20,
    # ld64.lld -> lld, llvm-lib -> llvm-ar), then prune bin/.
    keep = {name: None for name in rctx.attr.bins}
    bin_dir = rctx.path("bin")
    for name in rctx.attr.bins:
        tool = bin_dir.get_child(name)
        if tool.exists:
            keep[tool.realpath.basename] = None
    for entry in bin_dir.readdir():
        if entry.basename not in keep:
            rctx.delete(entry)

    # Prune everything outside bin/ and lib/clang/<ver>/include.
    for entry in rctx.path(".").readdir():
        if entry.basename not in ("bin", "lib"):
            rctx.delete(entry)
    lib_dir = rctx.path("lib")
    for entry in lib_dir.readdir():
        if entry.basename != "clang":
            rctx.delete(entry)
    for verdir in lib_dir.get_child("clang").readdir():
        for entry in verdir.readdir():
            if entry.basename != "include":
                rctx.delete(entry)

    rctx.file("BUILD.bazel", _BUILD.format(version = rctx.attr.version, host = key, consumer = rctx.attr.consumer), executable = False)

    # Opt into the repo contents cache: the fetch is a pure function of the
    # pinned URL+sha256 and the deterministic prune above, and the ~172 s
    # extraction of the 2 GiB archive was the single largest cost of every
    # fresh output base on ephemeral CI pods (profiled: run 30510579596).
    return rctx.repo_metadata(reproducible = True)

def _llvm_tools_repository(consumer, version, dists, bins):
    return repository_rule(
        implementation = _llvm_tools_impl,
        doc = "Pruned LLVM {} release binaries for the {} cross toolchain.".format(version, consumer),
        attrs = {
            "bins": attr.string_list(default = bins),
            "consumer": attr.string(default = consumer),
            # host key -> [release asset suffix, sha256]
            "dists": attr.string_list_dict(default = dists),
            "version": attr.string(default = version),
        },
    )

llvm_msvc_tools_repository = _llvm_tools_repository(
    consumer = "msvc",
    version = "20.1.7",
    dists = {
        "linux-arm64": ["Linux-ARM64", "832f2802a29457dc758f56e26e98558c6cd0e45fcd07186f540cb6e7f4e59385"],
        "linux-x64": ["Linux-X64", "8494c98a774051a40bfe1187a2d6442f4bc107598998bbe1673d9bb1572cfd6f"],
        "macos-arm64": ["macOS-ARM64", "6aa75de00575ad0663183b00f00f39992ded611b5136e57649ace1e6a53c0d16"],
        "macos-x64": ["macOS-X64", "ccf82ffe7e136ee49659cb57157856a7963d0950fac3d05aabba0db75bfba26f"],
    },
    bins = [
        "clang",
        "clang-cl",
        "lld",
        "lld-link",
        "llvm-ar",
        "llvm-lib",
        "llvm-ml",
        "llvm-mt",
        "llvm-rc",
    ],
)

llvm_darwin_tools_repository = _llvm_tools_repository(
    consumer = "darwin",
    version = "23.1.3",
    dists = {
        "linux-arm64": ["Linux-ARM64", "56d005e339c979a696ed6c244e6472e16f3b1371e48987a07e6145bda7ee0d03"],
        "linux-x64": ["Linux-X64", "ca9fe385a5d9e2d88132dc0e23a00e9f87f38fa75f67207b5e457d208e71d013"],
    },
    bins = [
        "clang",
        "clang++",
        "ld64.lld",
        "lld",
        "llvm-ar",
        "llvm-libtool-darwin",
        "llvm-nm",
        "llvm-objcopy",
        "llvm-ranlib",
        "llvm-strip",
    ],
)
