#!/usr/bin/env bun
/**
 * Pins pi-ast to a stencil-hq/wasm-grammars release: fetches its
 * `manifest.json` and regenerates `crates/pi-ast/src/language/wasm_grammars.rs`,
 * the table of WebAssembly grammars (file names, SHA-256 digests, sizes) the
 * addon loads and the agent downloads on demand.
 *
 * Usage:
 *   bun run gen:grammars                         # latest release
 *   bun run gen:grammars -- v3                   # a specific release tag
 *   bun run gen:grammars -- ./dist/manifest.json # a local wasm-grammars build
 *
 * A language pi-ast maps to a wasm grammar but the manifest lacks fails to
 * compile (`grammar!(wasm …)` in `crates/pi-ast/src/language/mod.rs`).
 */
import * as path from "node:path";
import { type } from "@oh-my-pi/omptype";

const REPO = "stencil-hq/wasm-grammars";
const REPO_ROOT = path.join(import.meta.dir, "..");
const TABLE = path.join(REPO_ROOT, "crates", "pi-ast", "src", "language", "wasm_grammars.rs");

/** A wasm-grammars release `manifest.json`; `tree_sitter` is the CLI version, which fixes the wasm ABI. */
const Manifest = type({
	release: "string > 0",
	tree_sitter: "string > 0",
	grammars: type({
		language: "string > 0",
		crate: "string > 0",
		version: "string > 0",
		symbol: "string > 0",
		file: "string > 0",
		sha256: /^[0-9a-f]{64}$/,
		size: "number.integer > 0",
	}).array(),
});
type Manifest = typeof Manifest.infer;

const source = process.argv[2] ?? "latest";
const manifest = Manifest.assert(await readManifest(source));
const runtime = await treeSitterRuntimeVersion();
const [builtMinor, runtimeMinor] = [manifest.tree_sitter, runtime].map(version =>
	version.split(".").slice(0, 2).join("."),
);
if (builtMinor !== runtimeMinor) {
	console.error(
		`gen-grammars: ${manifest.release} was built by tree-sitter-cli ${manifest.tree_sitter}, ` +
			`but pi-ast links tree-sitter ${runtime}; their wasm ABIs differ`,
	);
	process.exit(1);
}
await Bun.write(TABLE, renderTable(manifest));
console.log(
	`${path.relative(REPO_ROOT, TABLE)}: ${manifest.grammars.length} grammars from ${REPO} ${manifest.release}`,
);

async function readManifest(source: string): Promise<unknown> {
	if (source.endsWith(".json")) return Bun.file(source).json();
	const url =
		source === "latest"
			? `https://github.com/${REPO}/releases/latest/download/manifest.json`
			: `https://github.com/${REPO}/releases/download/${source}/manifest.json`;
	const response = await fetch(url);
	if (!response.ok) throw new Error(`fetching ${url}: HTTP ${response.status}`);
	return response.json();
}

/** Version of the `tree-sitter` runtime crate in Cargo.lock. */
async function treeSitterRuntimeVersion(): Promise<string> {
	const lock = await Bun.file(path.join(REPO_ROOT, "Cargo.lock")).text();
	const version = lock.match(/^name = "tree-sitter"\nversion = "([^"]+)"/m)?.[1];
	if (!version) throw new Error("Cargo.lock has no tree-sitter package");
	return version;
}

function renderTable(manifest: Manifest): string {
	const entries = manifest.grammars.map(
		grammar => `/// \`${grammar.crate}\` ${grammar.version}.
pub static ${grammar.language.toUpperCase().replaceAll("-", "_")}: WasmGrammar = WasmGrammar::new(
	"${grammar.language}",
	"${grammar.symbol}",
	"${grammar.file}",
	"${grammar.sha256}",
	${grammar.size},
);
`,
	);
	return `//! Generated by \`bun run gen:grammars\` from ${REPO} ${manifest.release}; do
//! not edit.
//!
//! WebAssembly grammars published as \`<file>.zst\` assets of that release (see
//! [\`super::grammar\`]).

use super::grammar::WasmGrammar;

/// ${REPO} release tag hosting every grammar below.
pub const RELEASE: &str = "${manifest.release}";

${entries.join("\n")}`;
}
