//! Fixture harness shared by every engine's integration tests.
//!
//! A fixture file (`tests/fixtures/<mode>/<group>.json`) holds
//! `{ "cases": [ … ] }`. Each case builds a temp workspace from `files`,
//! records optional `snapshots` into the store (so `{{tag:<path>}}` in the
//! args expands to the minted hashline tag), runs one [`Session`] through a
//! disk-backed writer, and compares written files / error text / result text
//! against `expect`.
//!
//! ```json
//! {
//!   "name": "…",
//!   "mode": "sloppy",                       // optional; defaults to the file's mode
//!   "files": { "a.ts": "…" },
//!   "args": { "input": "…" },               // JSON args (or "input": "…" shorthand for text modes)
//!   "rawInput": false,                      // optional: feed `input` as a verbatim custom-format payload
//!   "policy": { "allowFuzzy": true, "fuzzyThreshold": 0.95, "enforceSeenLines": false,
//!               "planActive": false, "blockAutoGenerated": true },
//!   "snapshots": [ { "path": "a.ts", "text": "…", "seenLines": [1,2] } ],
//!   "clipboard": { "named": { "reg": ["line"] } },
//!   "expect": {
//!     "files": { "a.ts": "…" },             // exact post-edit bytes
//!     "deleted": ["b.ts"],
//!     "error": "substring or ^regex$",
//!     "text": "exact result text",
//!     "textContains": ["…"],
//!     "writes": 0                           // number of writer calls
//!   }
//! }
//! ```
#![allow(dead_code, reason = "each test binary uses a subset of the harness")]

use std::path::{Path, PathBuf};

use async_trait::async_trait;
use parking_lot::Mutex;
use pi_edit::{
	ApplyOutcome, ApplyRequest, EditError, EditMode, EditResult, EditStore, EditWriter, FileOp,
	PathPolicy, Session, WriteRequest, WriteResponse, session::SessionConfig, store::Clipboard,
};
use serde_json::Value;

pub type RewriteFn = Box<dyn Fn(&WriteRequest) -> String + Send + Sync>;

/// Writer that persists to disk (so `expect.files` reflects the real
/// post-state) and records every request.
#[derive(Default)]
pub struct DiskWriter {
	pub requests: Mutex<Vec<WriteRequest>>,
	/// Optional override of the text the writer reports as persisted.
	pub rewrite:  Option<RewriteFn>,
	/// When set, the Nth (0-based) write fails with this message.
	pub fail_at:  Option<(usize, String)>,
}

#[async_trait]
impl EditWriter for DiskWriter {
	async fn write(&self, request: WriteRequest) -> EditResult<WriteResponse> {
		let index = {
			let mut requests = self.requests.lock();
			requests.push(request.clone());
			requests.len() - 1
		};
		if let Some((at, message)) = &self.fail_at
			&& *at == index
		{
			return Err(EditError::Writer(message.clone()));
		}
		let written = match request.op {
			FileOp::Delete => {
				std::fs::remove_file(&request.absolute)
					.map_err(|e| EditError::Writer(e.to_string()))?;
				String::new()
			},
			FileOp::Noop => String::new(),
			FileOp::Create | FileOp::Update => {
				let content = request.content.clone().unwrap_or_default();
				let text = self.rewrite.as_ref().map_or(content, |f| f(&request));
				let target = request
					.move_to
					.clone()
					.unwrap_or_else(|| request.absolute.clone());
				if let Some(parent) = target.parent() {
					std::fs::create_dir_all(parent).map_err(|e| EditError::Writer(e.to_string()))?;
				}
				std::fs::write(&target, &text).map_err(|e| EditError::Writer(e.to_string()))?;
				if request.move_to.is_some() {
					let _ = std::fs::remove_file(&request.absolute);
				}
				text
			},
		};
		Ok(WriteResponse { written, diagnostics_json: None })
	}
}

/// Temp workspace + store + config for one case.
pub struct Workspace {
	pub dir:    tempfile::TempDir,
	pub store:  EditStore,
	pub config: SessionConfig,
}

impl Workspace {
	pub fn new(mode: EditMode) -> Self {
		let dir = tempfile::tempdir().expect("tempdir");
		let cwd = dir.path().canonicalize().expect("canonical tempdir");
		let config = SessionConfig {
			mode,
			policy: PathPolicy {
				cwd:                  cwd.clone(),
				home_dir:             cwd,
				local_sandbox_root:   None,
				vault_roots:          None,
				plan_active:          false,
				block_auto_generated: true,
			},
			allow_fuzzy: true,
			fuzzy_threshold: 0.95,
			enforce_seen_lines: false,
			raw_input: false,
		};
		Self { dir, store: EditStore::new(), config }
	}

	pub fn cwd(&self) -> &Path {
		&self.config.policy.cwd
	}

	pub fn write(&self, rel: &str, text: &str) -> PathBuf {
		let path = self.cwd().join(rel);
		if let Some(parent) = path.parent() {
			std::fs::create_dir_all(parent).expect("mkdir");
		}
		std::fs::write(&path, text).expect("write fixture file");
		path
	}

	pub fn read(&self, rel: &str) -> Option<String> {
		std::fs::read_to_string(self.cwd().join(rel)).ok()
	}

	/// Record a snapshot (LF-normalized) and return its tag.
	pub fn snapshot(&self, rel: &str, text: &str, seen: Option<&[u32]>) -> String {
		let key = pi_edit::path_policy::canonical_key(&self.cwd().join(rel));
		self
			.store
			.record(&key, &pi_edit::text::normalize_to_lf(text), seen)
	}

	pub fn session(&self) -> Session {
		Session::new(self.config.clone(), self.store.clone())
	}

	/// Run a complete-args apply.
	pub async fn apply_json(&self, args: &Value, writer: &DiskWriter) -> EditResult<ApplyOutcome> {
		let mut session = self.session();
		session.set_args_json(&args.to_string());
		session.finish();
		session.apply(ApplyRequest::default(), writer).await
	}

	/// Run a raw-payload apply (custom-format tools).
	pub async fn apply_raw(&self, input: &str, writer: &DiskWriter) -> EditResult<ApplyOutcome> {
		let mut config = self.config.clone();
		config.raw_input = true;
		let mut session = Session::new(config, self.store.clone());
		session.push(input);
		session.finish();
		session.apply(ApplyRequest::default(), writer).await
	}
}

fn expect_matches(actual: &str, pattern: &str) -> bool {
	if let Some(rest) = pattern.strip_prefix('^') {
		let re = regex::Regex::new(&format!("^{rest}")).expect("valid expect regex");
		re.is_match(actual)
	} else {
		actual.contains(pattern)
	}
}

fn substitute_tags(value: &mut Value, tags: &[(String, String)]) {
	match value {
		Value::String(s) => {
			for (path, tag) in tags {
				let needle = format!("{{{{tag:{path}}}}}");
				if s.contains(&needle) {
					*s = s.replace(&needle, tag);
				}
			}
		},
		Value::Array(items) => items.iter_mut().for_each(|v| substitute_tags(v, tags)),
		Value::Object(map) => map.values_mut().for_each(|v| substitute_tags(v, tags)),
		_ => {},
	}
}

/// Run every case in a fixture file for `default_mode`.
pub async fn run_fixture(path: impl AsRef<Path>, default_mode: EditMode) {
	let path = Path::new(env!("CARGO_MANIFEST_DIR"))
		.join("tests/fixtures")
		.join(path);
	let text = std::fs::read_to_string(&path)
		.unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()));
	let root: Value = serde_json::from_str(&text)
		.unwrap_or_else(|e| panic!("parse fixture {}: {e}", path.display()));
	let cases = root["cases"].as_array().expect("fixture has cases");
	let mut failures = Vec::new();
	for case in cases {
		let name = case["name"].as_str().unwrap_or("<unnamed>").to_owned();
		if let Err(message) = run_case(case, default_mode).await {
			failures.push(format!("[{name}] {message}"));
		}
	}
	assert!(
		failures.is_empty(),
		"{} case(s) failed in {}:\n{}",
		failures.len(),
		path.display(),
		failures.join("\n\n")
	);
}

async fn run_case(case: &Value, default_mode: EditMode) -> Result<(), String> {
	let mode = case["mode"]
		.as_str()
		.map_or(default_mode, |m| EditMode::parse(m).expect("valid mode"));
	let mut ws = Workspace::new(mode);
	if let Some(policy) = case.get("policy") {
		if let Some(v) = policy["allowFuzzy"].as_bool() {
			ws.config.allow_fuzzy = v;
		}
		if let Some(v) = policy["fuzzyThreshold"].as_f64() {
			ws.config.fuzzy_threshold = v;
		}
		if let Some(v) = policy["enforceSeenLines"].as_bool() {
			ws.config.enforce_seen_lines = v;
		}
		if let Some(v) = policy["planActive"].as_bool() {
			ws.config.policy.plan_active = v;
		}
		if let Some(v) = policy["blockAutoGenerated"].as_bool() {
			ws.config.policy.block_auto_generated = v;
		}
	}
	if let Some(files) = case["files"].as_object() {
		for (rel, content) in files {
			ws.write(rel, content.as_str().expect("file content string"));
		}
	}
	let mut tags = Vec::new();
	if let Some(snapshots) = case["snapshots"].as_array() {
		for snap in snapshots {
			let rel = snap["path"].as_str().expect("snapshot path");
			let text = snap["text"]
				.as_str()
				.map(str::to_owned)
				.or_else(|| ws.read(rel))
				.expect("snapshot text or existing file");
			let seen: Option<Vec<u32>> = snap["seenLines"]
				.as_array()
				.map(|a| a.iter().map(|v| v.as_u64().expect("line") as u32).collect());
			let tag = ws.snapshot(rel, &text, seen.as_deref());
			tags.push((rel.to_owned(), tag));
		}
	}
	if let Some(named) = case["clipboard"]["named"].as_object() {
		let mut clipboard = Clipboard::default();
		let mut map = std::collections::HashMap::new();
		for (reg, lines) in named {
			map.insert(
				reg.clone(),
				lines
					.as_array()
					.expect("lines")
					.iter()
					.map(|l| l.as_str().unwrap().to_owned())
					.collect(),
			);
		}
		clipboard.named = Some(map);
		ws.store.commit_clipboard(&clipboard);
	}

	let mut args = match (case.get("args"), case.get("input")) {
		(Some(args), _) => args.clone(),
		(None, Some(input)) => serde_json::json!({ "input": input }),
		(None, None) => return Err("case has neither args nor input".into()),
	};
	substitute_tags(&mut args, &tags);
	let writer = DiskWriter::default();
	let outcome = if case["rawInput"].as_bool() == Some(true) {
		ws.apply_raw(args["input"].as_str().expect("raw input"), &writer)
			.await
	} else {
		ws.apply_json(&args, &writer).await
	};

	let expect = &case["expect"];
	let mut problems = Vec::new();
	match (&outcome, expect["error"].as_str()) {
		(Err(err), Some(pattern)) => {
			let actual = err.to_string();
			if !expect_matches(&actual, pattern) {
				problems.push(format!("error mismatch\n  expected: {pattern}\n  actual:   {actual}"));
			}
		},
		(Err(err), None) => problems.push(format!("unexpected error: {err}")),
		(Ok(_), Some(pattern)) => {
			problems.push(format!("expected error {pattern:?} but apply succeeded"));
		},
		(Ok(_), None) => {},
	}
	if let Ok(outcome) = &outcome {
		if let Some(text) = expect["text"].as_str()
			&& outcome.text != text
		{
			problems
				.push(format!("text mismatch\n  expected: {text:?}\n  actual:   {:?}", outcome.text));
		}
		if let Some(parts) = expect["textContains"].as_array() {
			for part in parts {
				let part = part.as_str().expect("textContains string");
				if !expect_matches(&outcome.text, part) {
					problems.push(format!("text missing {part:?}\n  actual: {:?}", outcome.text));
				}
			}
		}
	}
	if let Some(files) = expect["files"].as_object() {
		for (rel, content) in files {
			let expected = content.as_str().expect("expected file string");
			match ws.read(rel) {
				Some(actual) if actual == expected => {},
				Some(actual) => problems.push(format!(
					"file {rel} mismatch\n  expected: {expected:?}\n  actual:   {actual:?}"
				)),
				None => problems.push(format!("file {rel} missing after apply")),
			}
		}
	}
	if let Some(deleted) = expect["deleted"].as_array() {
		for rel in deleted {
			let rel = rel.as_str().expect("deleted path");
			if ws.cwd().join(rel).exists() {
				problems.push(format!("file {rel} should have been deleted"));
			}
		}
	}
	if let Some(writes) = expect["writes"].as_u64() {
		let actual = writer.requests.lock().len() as u64;
		if actual != writes {
			problems.push(format!("expected {writes} writes, got {actual}"));
		}
	}
	if problems.is_empty() {
		Ok(())
	} else {
		Err(problems.join("\n"))
	}
}
