/**
 * Glyph Protocol client: ships the TUI's private-use icons to the terminal so
 * the nerd symbol preset renders without a patched font installed.
 *
 * Transport is APC `ESC _ 25a1 ; <verb> [; k=v]* [; payload] ESC \` with four
 * verbs — `s` (support query), `q` (coverage query), `r` (register), `c`
 * (clear). {@link ProcessTerminal} drives the handshake: `s` behind its DA1
 * sentinel at startup; on a `glyf`-capable reply it writes
 * {@link encodeBundledGlyphRegistrations} in one shot followed by a `q` for
 * {@link GLYPH_CONFIRMATION_CODEPOINT}, and a `glossary` answer confirms the
 * bundle landed. Registrations are fire-and-forget (`reply=0`),
 * session-scoped, and confined to the PUA ranges, so they can never restyle
 * real text.
 *
 * Spec: https://github.com/raphamorim/rio/blob/main/specs/glyph-protocol.md
 * The bundle is generated by `scripts/gen-glyphs.ts` (`bun run gen:glyphs`).
 */
import bundle from "./theme/glyph-bundle.json" with { type: "json" };

/** Protocol identifier: U+25A1 WHITE SQUARE as lowercase hex. */
const GLYPH_PROTOCOL_ID = "25a1";
const APC = "\x1b_";
const ST = "\x1b\\";

/** One bundled outline: base64 simple-glyph record plus its scale policy. */
export interface GlyphBundleEntry {
	/** Base64 OpenType `glyf` simple-glyph record (§8.2 subset). */
	glyf: string;
	/** Fill the cell edge to edge (`size=stretch`, powerline); otherwise `size=contain`. */
	stretch?: boolean;
}

/** Generated icon bundle: shared design metrics plus outlines keyed by lowercase hex codepoint. */
export interface GlyphBundle {
	upm: number;
	/** Authored advance width — identical for every glyph of a Mono face. */
	aw: number;
	/** Authored line height (ascender − descender); outlines are lifted so y=0 is the descender line. */
	lh: number;
	glyphs: Record<string, GlyphBundleEntry>;
}

export const GLYPH_BUNDLE: GlyphBundle = bundle;

/**
 * Codepoint the handshake queries after registration to confirm the bundle
 * was accepted: the omp mark (`icon.omp`), which the status line always shows.
 */
export const GLYPH_CONFIRMATION_CODEPOINT = 0xf0d57;

/** Terminal reply to any Glyph Protocol verb, decoded from its APC body. */
export type GlyphProtocolReply =
	| { verb: "s"; formats: string[] }
	| { verb: "q"; cp: number; coverage: string[] }
	| { verb: "r"; cp: number; status: number; reason?: string }
	| { verb: "c"; status: number; reason?: string };

/** Whether `cp` lies in one of the three Private Use Areas the protocol accepts. */
export function isPrivateUseCodepoint(cp: number): boolean {
	return (cp >= 0xe000 && cp <= 0xf8ff) || (cp >= 0xf0000 && cp <= 0xffffd) || (cp >= 0x100000 && cp <= 0x10fffd);
}

/** `s` verb: doubles as the protocol-detection ping (any reply confirms support). */
export function encodeGlyphSupportQuery(): string {
	return `${APC}${GLYPH_PROTOCOL_ID};s${ST}`;
}

/** `q` verb: ask which sources (system font, session glossary) render `cp`. */
export function encodeGlyphCoverageQuery(cp: number): string {
	return `${APC}${GLYPH_PROTOCOL_ID};q;cp=${cp.toString(16)}${ST}`;
}

/**
 * `r` verb for one bundled outline at `cp`. Layout hints follow the bundle's
 * design metrics; `reply=0` suppresses the acknowledgement so bulk startup
 * registration leaves nothing on stdin to drain.
 */
export function encodeGlyphRegistration(
	cp: number,
	entry: GlyphBundleEntry,
	metrics: GlyphBundle = GLYPH_BUNDLE,
): string {
	if (!isPrivateUseCodepoint(cp))
		throw new RangeError(`U+${cp.toString(16).toUpperCase()} is not a private-use codepoint`);
	const size = entry.stretch ? "stretch" : "contain";
	return `${APC}${GLYPH_PROTOCOL_ID};r;cp=${cp.toString(16)};reply=0;upm=${metrics.upm};aw=${metrics.aw};lh=${metrics.lh};size=${size};${entry.glyf}${ST}`;
}

/** Every bundled icon as one contiguous write. */
export function encodeBundledGlyphRegistrations(metrics: GlyphBundle = GLYPH_BUNDLE): string {
	let out = "";
	for (const hex in metrics.glyphs) {
		out += encodeGlyphRegistration(Number.parseInt(hex, 16), metrics.glyphs[hex]!, metrics);
	}
	return out;
}

/** Whether `sequence` is a complete Glyph Protocol APC message. */
export function isGlyphProtocolSequence(sequence: string): boolean {
	return sequence.startsWith(`${APC}${GLYPH_PROTOCOL_ID};`) && sequence.endsWith(ST);
}

/**
 * Decode a terminal reply. Returns null for anything that is not a well-formed
 * Glyph Protocol message; unknown keys are ignored per §11 so future
 * parameters never break detection.
 */
export function parseGlyphProtocolReply(sequence: string): GlyphProtocolReply | null {
	if (!isGlyphProtocolSequence(sequence)) return null;
	const body = sequence.slice(APC.length + GLYPH_PROTOCOL_ID.length + 1, -ST.length);
	const parts = body.split(";");
	const verb = parts[0];
	const params: Record<string, string> = {};
	for (let i = 1; i < parts.length; i++) {
		const part = parts[i]!;
		const eq = part.indexOf("=");
		if (eq > 0) params[part.slice(0, eq)] = part.slice(eq + 1);
	}
	// Empty list values (`fmt=` / `status=`) mean "none", not one empty name.
	const list = (value: string | undefined): string[] => (value ? value.split(",") : []);
	switch (verb) {
		case "s":
			return { verb, formats: list(params.fmt) };
		case "q": {
			const cp = Number.parseInt(params.cp ?? "", 16);
			if (!Number.isFinite(cp)) return null;
			return { verb, cp, coverage: list(params.status) };
		}
		case "r": {
			const cp = Number.parseInt(params.cp ?? "", 16);
			const status = Number.parseInt(params.status ?? "", 10);
			if (!Number.isFinite(cp) || !Number.isFinite(status)) return null;
			return params.reason === undefined ? { verb, cp, status } : { verb, cp, status, reason: params.reason };
		}
		case "c": {
			const status = Number.parseInt(params.status ?? "", 10);
			if (!Number.isFinite(status)) return null;
			return params.reason === undefined ? { verb, status } : { verb, status, reason: params.reason };
		}
		default:
			return null;
	}
}
