/**
 * Compat-rule compiler entry: reads a `rules/` tree (taxonomy, classes,
 * providers, runtime) and compiles it into one {@link CompiledCompatRules}
 * value. Pure — importable from tests; the `gen:compat` CLI
 * (`scripts/compile-compat.ts`) persists the result as `rules.json`.
 */
import * as fs from "node:fs/promises";
import * as path from "node:path";
import type { CompiledAuth, CompiledCompatRules } from "../../src/compat/types";
import { compileAuth } from "./compile-auth";
import { compileBehavior } from "./compile-behavior";
import { compileCascade } from "./compile-cascade";
import { compileTaxonomy } from "./compile-taxonomy";

export { CompatCompileError } from "./kdl-reader";

interface RuleSource {
	/** `rules/`-relative path, forward slashes. */
	file: string;
	text: string;
}

async function readGroup(rulesDir: string, group: string): Promise<RuleSource[]> {
	let entries: string[];
	try {
		entries = await fs.readdir(path.join(rulesDir, group));
	} catch {
		return [];
	}
	const sources: RuleSource[] = [];
	for (const name of entries.sort()) {
		if (!name.endsWith(".kdl")) continue;
		const file = `${group}/${name}`;
		sources.push({ file, text: await Bun.file(path.join(rulesDir, file)).text() });
	}
	return sources;
}

/** Compiles the KDL rule tree rooted at `rulesDir` (deterministic output). */
export async function compileCompatRules(rulesDir: string): Promise<CompiledCompatRules> {
	const [taxonomy, classes, providers, runtime, auth] = await Promise.all([
		readGroup(rulesDir, "taxonomy"),
		readGroup(rulesDir, "classes"),
		readGroup(rulesDir, "providers"),
		readGroup(rulesDir, "runtime"),
		readGroup(rulesDir, "auth"),
	]);
	const behaviorSource = runtime.find(source => source.file === "runtime/behavior.kdl");
	const files = [...taxonomy, ...classes, ...providers, ...runtime, ...auth].map(source => source.file).sort();
	return {
		version: 1,
		files,
		taxonomy: compileTaxonomy(taxonomy),
		cascade: compileCascade([...classes, ...providers]),
		behavior: compileBehavior(behaviorSource),
		auth: compileAuth(auth),
	};
}

/**
 * Source of the committed `src/compat/auth-ids.ts`: literal id unions derived
 * from the compiled auth stratum so `@oh-my-pi/pi-ai` keeps typed provider
 * ids without importing the JSON as a const.
 */
export function renderAuthIds(auth: CompiledAuth): string {
	// oxfmt shape: short unions inline, long ones one member per line, so formatting never drifts.
	const union = (ids: string[]) => {
		if (ids.length === 0) return " never";
		const inline = ` ${ids.map(id => JSON.stringify(id)).join(" | ")}`;
		return inline.length + "export type LoginProviderId =;".length <= 120
			? inline
			: `\n${ids.map(id => `\t| ${JSON.stringify(id)}`).join("\n")}`;
	};
	const all = auth.providers.map(p => p.id).sort();
	const loginable = auth.providers
		.filter(p => p.login)
		.map(p => p.id)
		.sort();
	return [
		"// Generated by `bun run gen:compat` from `src/compat/rules/auth/*.kdl`; do not edit.",
		"",
		"/** Every provider with an `auth/<id>.kdl` policy. */",
		`export type AuthProviderId =${union(all)};`,
		"",
		"/** Providers whose policy declares a `login` flow (the `/login` roster). */",
		`export type LoginProviderId =${union(loginable)};`,
		"",
	].join("\n");
}
