import * as fs from "node:fs/promises";
import * as path from "node:path";
import type { AgentBinaries, GatewayConfig, GuestArch } from "./types";
import type { TrialVm } from "./vmon";

const REPO_ROOT = path.resolve(import.meta.dir, "../../../..");
const CODING_AGENT_DIR = path.join(REPO_ROOT, "packages", "coding-agent");
const NATIVES_DIR = path.join(REPO_ROOT, "packages", "natives", "native");

function shellQuote(value: string): string {
	return `'${value.replaceAll("'", `'"'"'`)}'`;
}

async function run(command: string[], cwd?: string): Promise<void> {
	const process = Bun.spawn(command, { cwd, stdout: "inherit", stderr: "inherit" });
	const exitCode = await process.exited;
	if (exitCode !== 0) throw new Error(`${command.join(" ")} exited with code ${exitCode}`);
}
/**
 * Refresh cross-target `pi_natives.linux-<arch>*.node` files in
 * `packages/natives/native/` from the published npm leaf package.
 *
 * The binary build embeds whatever `.node` files sit in that directory; on a
 * non-linux host they are stale local cross-builds that can fail `dlopen`
 * inside task guests (undefined libstdc++ symbols). The matching published
 * leaf is the artifact real installs load, so it is the ground truth for
 * embedding; an unpublished working-tree version fails instead of risking
 * loader/API skew.
 */
async function refreshCrossNatives(arches: GuestArch[], version: string): Promise<void> {
	for (const arch of arches) {
		if (process.platform === "linux" && process.arch === arch) continue;
		const pkg = `pi-natives-linux-${arch}`;
		const response = await fetch(`https://registry.npmjs.org/@oh-my-pi/${pkg}/-/${pkg}-${version}.tgz`);
		if (!response.ok) throw new Error(`Fetching @oh-my-pi/${pkg}@${version} failed: HTTP ${response.status}`);
		const archive = new Bun.Archive(await response.arrayBuffer());
		let extracted = 0;
		for (const [entry, file] of await archive.files()) {
			const name = path.posix.basename(entry);
			if (!name.startsWith(`pi_natives.linux-${arch}`) || !name.endsWith(".node")) continue;
			await Bun.write(path.join(NATIVES_DIR, name), file);
			extracted++;
		}
		if (extracted === 0) throw new Error(`@oh-my-pi/${pkg}@${version} tarball contained no .node files`);
	}
}

/** Build and cache self-contained omp binaries for the selected guest architectures. */
export async function prepareAgentBinaries(opts: {
	arches: GuestArch[];
	cacheDir: string;
	rebuild: boolean;
}): Promise<AgentBinaries> {
	const manifest = (await Bun.file(path.join(CODING_AGENT_DIR, "package.json")).json()) as { version?: unknown };
	if (typeof manifest.version !== "string" || manifest.version.length === 0) {
		throw new Error("packages/coding-agent/package.json has no valid version");
	}

	const arches = [...new Set(opts.arches)];
	const cached: Partial<Record<GuestArch, string>> = {};
	for (const arch of arches) {
		cached[arch] = path.join(opts.cacheDir, `omp-linux-${arch}-${manifest.version}`);
	}
	const missing: GuestArch[] = [];
	for (const arch of arches) {
		if (opts.rebuild || !(await Bun.file(cached[arch]!).exists())) missing.push(arch);
	}

	if (missing.length > 0) {
		await fs.mkdir(opts.cacheDir, { recursive: true });
		await refreshCrossNatives(missing, manifest.version);
		const targets = missing.map(arch => `linux-${arch}`).join(",");
		await run(["bun", "scripts/ci-release-build-binaries.ts", "--targets", targets], REPO_ROOT);
		for (const arch of missing) {
			const source = path.join(CODING_AGENT_DIR, "binaries", `omp-linux-${arch}`);
			const destination = cached[arch]!;
			if (!(await Bun.file(source).exists())) throw new Error(`Binary build did not produce ${source}`);
			await Bun.write(destination, Bun.file(source));
			await fs.chmod(destination, 0o755);
		}
	}

	const binaries: AgentBinaries = { version: manifest.version };
	for (const arch of arches) binaries[arch] = cached[arch];
	return binaries;
}

/** Install omp and gateway-only configuration into one running trial microVM. */
export async function installAgent(vm: TrialVm, binaries: AgentBinaries, gateway: GatewayConfig): Promise<string> {
	const binary = binaries[vm.arch];
	if (!binary) throw new Error(`No omp binary available for guest architecture ${vm.arch}`);

	const entrypoint = "/opt/omp/omp";
	const mkdir = await vm.exec("mkdir -p /opt/omp");
	if (mkdir.exitCode !== 0) throw new Error(`Could not create /opt/omp: ${mkdir.stderr.trim()}`);
	await vm.copyTo(binary, entrypoint);
	const chmod = await vm.exec(`chmod 755 ${shellQuote(entrypoint)}`);
	if (chmod.exitCode !== 0) throw new Error(`Could not make omp executable: ${chmod.stderr.trim()}`);
	const warmup = await vm.exec(`${shellQuote(entrypoint)} --version`);
	if (warmup.exitCode !== 0) throw new Error(`omp --version failed: ${warmup.stderr.trim()}`);

	const providers = [...new Set(gateway.providers)];
	const modelLines = ["# Generated by metaharness — auth via host pm2 gateway.", "providers:"];
	for (const provider of providers) {
		modelLines.push(`  ${provider}:`);
		modelLines.push(`    baseUrl: ${gateway.url}`);
		modelLines.push("    auth: oauth");
		modelLines.push("    transport: pi-native");
		modelLines.push(`    apiKey: ${gateway.token}`);
	}
	const modelsYaml = `${modelLines.join("\n")}\n`;
	const configYaml = `providers:
  openrouterVariant: ${gateway.openrouterVariant}
modelRoles:
  vision: openrouter/qwen/qwen3.7-flash
edit:
  mode: replace
web_search:
  enabled: false
`;
	const writeConfig = await vm.exec(
		`mkdir -p "$HOME/.omp/agent"\ncat > "$HOME/.omp/agent/models.yml" <<'OMP_MODELS_EOF'\n${modelsYaml}OMP_MODELS_EOF\ncat > "$HOME/.omp/agent/config.yml" <<'OMP_CONFIG_EOF'\n${configYaml}OMP_CONFIG_EOF`,
	);
	if (writeConfig.exitCode !== 0) throw new Error(`Could not install omp configuration: ${writeConfig.stderr.trim()}`);
	return entrypoint;
}
